### ISSUE TITLE
Can't leave build.snapcraft.io page up

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#1003]
If you leave leave a repo page up long enough, eventually you'll see an unauthorised error:
<img width="1094" alt="screen shot 2017-11-08 at 15 29 13" src="https://user-images.githubusercontent.com/1523179/32531777-f19dc248-c499-11e7-94b6-95c9d71d5984.png">

It gets worse if you navigate back to your dashboard, where it will claim you have no repos:
<img width="1104" alt="screen shot 2017-11-08 at 15 29 51" src="https://user-images.githubusercontent.com/1523179/32531780-f853f9f4-c499-11e7-93f6-6f53d9d944b8.png">

Because:
https://build.snapcraft.io/api/launchpad/snaps/list?owner=evandandrea
```{"status":"error","body":{"code":"token-not-valid","message":"CSRF token not valid"}}```

**Comment by bartaz** [comment]
Yes, we don't handle 401s very well.
Because it's a single page app and doesn't do a full reload only API calls return 401s when session timeouts. I guess when we detect that we should sign out the user so that they need to sign back in to renew the session - just as regular web app would work.

**Comment by evandandrea** [comment]
Could we sign them out and keep them on the same page? A full page refresh is fine, I just don't want to send someone back to build.snapcraft.io/ when they were on build.snapcraft.io/user/heroku/cli

**Comment by bartaz** [comment]
Yes, in theory refreshing repo page should be enough to refresh the user state and keep them on same page. At least in case of repo page or build page (that are accessible for not logged in users).

When you are on 'My repos' it gets more complicated, because you are required to be signed in there, so refreshing would redirect to home page.

**Comment by evandandrea** [comment]
I’ve seen this happen to @flexiondotorg and others recently.

**Comment by Lukewh** [comment]
A nice solution would be to have an overlay that says "your session has expired, please sign in again"

**Comment by Lukewh** [comment]
To do:

- Remove CSRF on public GET requests
- Add overlay, when the session has expired, to prompt explain and prompt to login again
- Increase CSRF token limit
