### ISSUE TITLE
"No repos" frequently shown - page slow to load

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#1006]
Visiting https://build.snapcraft.io/user/popey frequently gives me the text "No repos" in the middle. Which is a bit alarming. Then some time passes and it loads. I realise I probably have more snaps (via snapcrafters) than most, but it's a bit disconcerting to keep being told there's "no repos" when I know there are. If I wait a while it eventually loads.

**Comment by evandandrea** [comment]
Yes, I’ve seen this as well. We should have a “checking, just a minute” type message.

**Comment by matthewpaulthomas** [comment]
[From the spec](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.5c3e9xiupuq5):
> The table headers should appear immediately. If the list of repos has taken more than two seconds so far to load, a spinner should appear centered in the table.

However, I followed this with text that was imprecise: “Whenever there are no repos in the table …  the table should contain only the centered text ‘No repos’.” I’ve just changed this to “When you have no repos configured for building…”

**Comment by Lukewh** [comment]
As a first step we will:

Improve messaging - indicate when something is happening/ has happened, be it loading still, timing out or any other state.

A longer term solution:

- Optimise the requests made to Github (currently we wait for all the requests to return before showing anything in the UI)
- Improve UX of loading a lot of repos (progressive loading or something else)

**Comment by bartaz** [comment]
Now that I was added to `snapcrafters` and have ~70 repos on my list I almost always have this problem when first logging into BSI after some time.

My process is:
- Sign in
- 'My repos' shows spinner for quite long time
- Ends up showing No repos
- In console I can see that there was a timeout on loading list of repositories `Failed to load resource: the server responded with a status of 504 (Gateway Time-out)`

When I refresh the page it usually takes some time, but eventually loads properly.

The request that times out (listing of repos) consists of:
- calling LP for list of repos of given user (and their orgs)
- calling GH for each repo to fetch snapcraft.yaml data

When first logging in snapcraft.yaml data for repos in likely not in memcached anymore therefore BSI needs to call GH for all (70) repos. My suspision is that it takes too much time and times out. Next time (after refresh) at least some of repos are already memcached, so response is quicker and doesn't time out.

First of all - we need to properly show errors when loading repos (not to end up with 'No repos' and no explanation).
Then we need to figure out the way how to improve performance of listing of the repos.
It should either not call for all repos at once (to avoid waiting for all 70), or call just for listing of repos and call for snapcraft data separately from front-end (but this will mean we show repos without knowing if they are configured first).

**Comment by matthewpaulthomas** [comment]
@Lukewh Are you sure this is fixed? On staging I have only 3 repos, but when I Shift+reload it still says “No repos” for a second or two before showing the spinner.
