### ISSUE TITLE
First time flow skips snapcraft.yaml creation

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#1010]
<img width="1440" alt="screen shot 2017-11-13 at 14 23 39" src="https://user-images.githubusercontent.com/1523179/32705963-57375b36-c87e-11e7-936c-43c20084293d.png">

Steps to reproduce:

1. Clear all build.staging.snapcraft.io and  cookies, disconnect build.staging.snapcraft.io in GitHub settings
1. Log into build.staging.snapcraft.io as a first time user
1. Select one of your repos
1. Sign into SSO and register a name

What happens:

* "All set up! Your first build is on the way."

What should happen:

1. "Name and yaml" in the progress bar remains unchecked
1. The accordion switches to the "configured" drop down
1. You are guided to create a snapcraft.yaml

**Comment by bartaz** [comment]
Confirmed as a bug.
This is a regression, as this functionality used to work as expected.
