### ISSUE TITLE
First time flow skips repo selection

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#1011]
<img width="1440" alt="screen shot 2017-11-13 at 14 41 21" src="https://user-images.githubusercontent.com/1523179/32706245-c7614abe-c880-11e7-986e-d55c872462ca.png">

Steps to reproduce:

1. Clear all build.staging.snapcraft.io and github.com cookies, disconnect build.staging.snapcraft.io in GitHub OAuth settings
1. Visit build.staging.snapcraft.io, click the CTA
1. Authorise use of your GitHub details

What happens:

* You are brought to a page that says "No repos"

What should happen:

* You are shown the first time flow progress bar
* You are shown the /select-repositories page

**Comment by shivjoshi1996** [comment]
Me and Greg sat down and created a snapcraft profile.

1. Authorised Github
  - No progress bar
  - But does take me to add repo modal

![screenshot from 2017-11-24 11-01-14](https://user-images.githubusercontent.com/33127429/33208082-139109f8-d108-11e7-93ba-073c268b82f8.png)

2. Select repo
  - Shows progress, with all three stages ticked (same as the bug in [this](https://app.zenhub.com/workspace/o/canonical-websites/build.snapcraft.io/issues/1010))

![screenshot from 2017-11-24 11-03-03](https://user-images.githubusercontent.com/33127429/33208090-21bc5726-d108-11e7-8595-cd11cdcf1405.png)

**Comment by bartaz** [comment]
Thanks for checking this.

Yes, it shouldn't happen for new users.

I checked in the codebase and it is an expected behaviour for a user who added snaps before and removed them all.

It was introduced as a bugfix in #802.
