### ISSUE TITLE
Expired certificate on build.staging.snapcraft.io

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/build.snapcraft.io#1024]
## Summary

Can't access build.staging.snapcraft.io because of expired certificate:

<img width="930" alt="screen shot 2017-12-08 at 09 42 17" src="https://user-images.githubusercontent.com/83575/33757843-3e36b186-dbfc-11e7-88d7-d3c1b24081da.png">

**Comment by cjwatson** [comment]
On it, but I need to wait for approval on my updated certificate request.

**Comment by cjwatson** [comment]
I've updated the certificate now.

**Comment by bartaz** [comment]
Thanks!
