### ISSUE TITLE
Use snapcraft from stable

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#1028]
snapcraft is now available in the stable channel. We should update the copy accordingly.

```
alan@deep-thought:~$ snap info snapcraft
name:      snapcraft
summary:   easily create snaps
publisher: canonical
contact:   snappy-canonical-storeaccount@canonical.com
description: |
  Snapcraft aims to make upstream developers' lives easier and as such is not a
  single toolset, but instead is a collection of tools that enable the natural
  workflow of an upstream to be extended with a simple release step into Snappy
  enabled system.
snap-id: vMTKRaLjnOJQetI78HjntT37VuoyssFE
commands:
  - snapcraft
tracking:    edge
installed:   2.37+git3.1a7a4f7 (938) 53MB classic
refreshed:   2017-12-11 23:44:28 +0000 UTC
channels:                            
  stable:    2.35              (794) 53MB classic
  candidate: ↑                            
  beta:      2.37              (924) 53MB classic
  edge:      2.37+git3.1a7a4f7 (938) 53MB classic

```

**Comment by cjwatson** [comment]
Not a build.snapcraft.io bug; please file this against launchpad-buildd.  (I've already had discussions with Sergio et al about this and we have a sketch of a plan.)

**Comment by evandandrea** [comment]
It's both, actually. We need [the copy text for when a build fails](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.fb6xz08fuya5).

**Comment by evandandrea** [comment]
Ah, re-reading I see that the request asked for switching from the deb in response to snapcraft being in stable. I've rewording the request to be relevant to build.snapcraft.io.

**Comment by bartaz** [comment]
@evandandrea So what should build failed instruction say now? `sudo snap install snapcraft # if you don’t have snapcraft already`?

**Comment by bartaz** [comment]
Ah, it still needs `--classic`:

`sudo snap install --classic snapcraft # if you don’t have snapcraft already`

**Comment by evandandrea** [comment]
Yup, that's right, `sudo snap install --classic snapcraft # if you don't have snapcraft already`
