### ISSUE TITLE
Cannot set auto release for repository

### ISSUE THREAD

**Issue by aquilax** [canonical-websites/build.snapcraft.io#1038]
## Summary

Cannot set up auto build

## Process

I am following (this guide)[https://docs.snapcraft.io/build-snaps/go].
After selecting the repository I get a message "To release in the snap store, this repo needs a registered name. You need to sign in to Ubuntu One to register a name."

Pressing the Sign In button does nothing and generates JS error:

bundle.3dc1233264240632f579.js:23 Uncaught (in promise) DOMException
n.onabort.n.onerror @ bundle.3dc1233264240632f579.js:23

## Current and expected result

Expected to be able to set up the auto build

## Screenshot

![bgwylgx](https://user-images.githubusercontent.com/328067/34317812-1d44a6a6-e7b7-11e7-9f17-eadabf3364a4.png)

**Comment by bartaz** [comment]
Sorry for not getting back on that for that long.
In the meantime we released multiple bugfixes, and at this point I can't reproduce the issue mentioned here.
Does it still happen? If so it may be related to your account and we will need more details to track it.

Feel free to reopen this if you are still experiencing this issue.
