### ISSUE TITLE
dont build at github update

### ISSUE THREAD

**Issue by rimtzg** [canonical-websites/build.snapcraft.io#1039]
## Summary

The page dont build my repo supertpv-print-server

## Process

Befor 2 days ago the auto build work fine, now I update my repo and dont build, I click in the button "Build manually now" and dont work

## Current and expected result

I relase commits and commits and the page no build the new relase

## Screenshot

[if relevant, include a screenshot]

**Comment by cjwatson** [comment]
https://twitter.com/launchpadstatus/status/948688233029881856

We'll hopefully have a banner up on build.snapcraft.io about this shortly.

**Comment by rimtzg** [comment]
I don't see the banner, but thank you, I follow the Twitter account.
