### ISSUE TITLE
Queued builds not appearing

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#1041]
Hitting Build manually now works:

```json
{"repository_url":"https://github.com/evandandrea/tensorflow-snap"}
```

```json
{"status":"success","payload":{"code":"snap-builds-requested","builds":[],"build_annotations":{}}}
```

But the confirmed queued builds,

<img width="1064" alt="screen shot 2018-01-11 at 09 16 43" src="https://user-images.githubusercontent.com/1523179/34812870-45791686-f6b0-11e7-8a1e-60c84f275fae.png">

Do not appear:

<img width="1051" alt="screen shot 2018-01-11 at 09 16 10" src="https://user-images.githubusercontent.com/1523179/34812869-45506dbc-f6b0-11e7-8f64-4ce760c65c97.png">

**Comment by evandandrea** [comment]
I can confirm the same happens for another snap (Atom):

```
{"status":"success","payload":{"code":"snap-builds-requested","builds":[],"build_annotations":{}}}
```
<img width="1074" alt="screen shot 2018-01-11 at 09 26 36" src="https://user-images.githubusercontent.com/1523179/34813188-a8006ee8-f6b1-11e7-9c8d-e3ef5b32a84f.png">
<img width="1058" alt="screen shot 2018-01-11 at 09 27 12" src="https://user-images.githubusercontent.com/1523179/34813189-a82b8588-f6b1-11e7-870d-1767e1196811.png">

**Comment by bartaz** [comment]
It seems that LP API doesn't return these queued builds, so BSI doesn't know they exist.
Not sure if it's an issue related to the maintenance or something else.

**Comment by cjwatson** [comment]
It's unrelated to maintenance, except for the build queues being long.

`snap.builds` doesn't have quite the right ordering for BSI.  I would suggest that `internalGetSnapBuilds` should do the following:

 * fetch `snap.pending_builds_collection_link`
 * if there are fewer than `size` elements in the response, then fill out the remaining requested size of the collection from `snap.completed_builds_collection_link`

**Comment by bartaz** [comment]
@cjwatson Ok, thanks for heads up.
