### ISSUE TITLE
'on' 'else' attributes for environment variables.

### ISSUE THREAD

**Issue by bsutton** [canonical-websites/build.snapcraft.io#1051]
## Add the ability to customize environment variables based on architecture.

I'm doing raspberry pi development and use an environment variable to enable/disable a hardware simulator.
When the snap is being deployed into a test (non-arm64) environment I need to set a number of environment variables to enable the simulator and disable the loading of the .so file (the application is java but the hardware interface is in a .so).

I came across the 'on' 'else' keywords and they look perfect for this sort of problem.

I want to be able to write:
```
apps:
    pi-gation:
      command: tomcat-launch
      daemon: simple
      plugs: [network, network-bind]
      on arm64:
        environment:
            PI4J_PLATFORM : RaspberryPi GPIO Provider
      else:
        environment:
          PI4J_PLATFORM : Simulated
          SimulatedPlatform : RaspberryPi GPIO Provider
```

## Process

As this is an enhancement request...

## Current and expected result

Currently the on..else keywords are only supported for the 'stage-packages' key word.

on..else should be supported for setting environment variables.

Possibly the concept should be considered for a number of other properties.

## Screenshot

[if relevant, include a screenshot]

**Comment by cjwatson** [comment]
build.snapcraft.io is just a build frontend - the details of `snapcraft.yaml` syntax are out of our hands.  Could you please re-file this against snapcraft (both https://github.com/snapcore/snapcraft/issues and https://bugs.launchpad.net/snapcraft exist, but I think the latter is preferred) and then close this issue?  Thanks.

**Comment by bsutton** [comment]
sorry, I've now moved it to launchpad.
