### ISSUE TITLE
Build Service Launchpad login process fails with "Invalid association handle"

### ISSUE THREAD

**Issue by diddledan** [canonical-websites/build.snapcraft.io#1054]
## Summary

Build service refuses to let me login with my launchpad credentials (~diddledan). I have 2FA enabled using a Yubikey but was not prompted for the code. It reports "Invalid association handle".

## Process

1. Login to launchpad.net with your 2FA-enabled account.
1. Login to build.snapcraft.io with github account.
1. Choose unassigned repo and add to the list of snap repos.
1. Click to register a snap name for the newly added repo.
1. Click the Login button to fetch launchpad token.
1. Revel in error when you return from the redirects, and notice that you weren't prompted for the 2FA code nor login details (the latter being because you already authenticated to launchpad.net first) :-)

## Current and expected result

Current reports an error message "Invalid association handle".

Expected to login successfully and allow choosing snap name to register to the store.

## Screenshot

![image](https://user-images.githubusercontent.com/147548/35656362-e0dc41c4-06ab-11e8-8f96-db825583edd7.png)

### Request
POST /login/verify?starting_url=https%3A%2F%2Fbuild.snapcraft.io%2Fuser%2Fdiddledan&caveat_id=%7B%22secret%22%3A%20%22J2Ou1uDwoB7yzgtl4vwYfMIBrFrQoHa7%2Bp2Jt15bV%2B%2BxdRdAm%2F6U%2FrvbNfVfyutc5Fz1vvie0K4BqrhqJpEx5Mm4cGwdtkslevGNg8nXvamDErgune85a3TCK1SiAfLagT9K4zDmEmr7rthzkMt0JUt6uX%2Fi%2F%2BkYXdMdvWU90ZjfpMPc0E3SPsWR7WfaxnpkWkMLMtAY0EYWSSZcOoGuxjILjIAxs3VFdDErzGEj4e%2F8GVcRWENZ1WGknhKYGaGepnx9KJPUadIpPbl2pYGyYjQy1XYDnG3gU%2FVA9DqoSfdp%2FTtT%2BlQ44sux2kuaU5KHZRhUiMQhxIdxjXXc%2BuUwvg%3D%3D%22%2C%20%22version%22%3A%201%7D HTTP/1.1
Host: build.snapcraft.io
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://login.ubuntu.com/+openid?openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.sreg.required=nickname%2Cemail%2Cfullname&openid.ns.macaroon=http%3A%2F%2Fns.login.ubuntu.com%2F2016%2Fopenid-macaroon&openid.macaroon.caveat_id=%7B%22secret%22%3A%20%22J2Ou1uDwoB7yzgtl4vwYfMIBrFrQoHa7%2Bp2Jt15bV%2B%2BxdRdAm%2F6U%2FrvbNfVfyutc5Fz1vvie0K4BqrhqJpEx5Mm4cGwdtkslevGNg8nXvamDErgune85a3TCK1SiAfLagT9K4zDmEmr7rthzkMt0JUt6uX%2Fi%2F%2BkYXdMdvWU90ZjfpMPc0E3SPsWR7WfaxnpkWkMLMtAY0EYWSSZcOoGuxjILjIAxs3VFdDErzGEj4e%2F8GVcRWENZ1WGknhKYGaGepnx9KJPUadIpPbl2pYGyYjQy1XYDnG3gU%2FVA9DqoSfdp%2FTtT%2BlQ44sux2kuaU5KHZRhUiMQhxIdxjXXc%2BuUwvg%3D%3D%22%2C%20%22version%22%3A%201%7D&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=%7BHMAC-SHA256%7D%7B5a726c5e%7D%7B10vyyg%3D%3D%7D&openid.return_to=https%3A%2F%2Fbuild.snapcraft.io%2Flogin%2Fverify%3Fstarting_url%3Dhttps%253A%252F%252Fbuild.snapcraft.io%252Fuser%252Fdiddledan%26caveat_id%3D%257B%2522secret%2522%253A%2520%2522J2Ou1uDwoB7yzgtl4vwYfMIBrFrQoHa7%252Bp2Jt15bV%252B%252BxdRdAm%252F6U%252FrvbNfVfyutc5Fz1vvie0K4BqrhqJpEx5Mm4cGwdtkslevGNg8nXvamDErgune85a3TCK1SiAfLagT9K4zDmEmr7rthzkMt0JUt6uX%252Fi%252F%252BkYXdMdvWU90ZjfpMPc0E3SPsWR7WfaxnpkWkMLMtAY0EYWSSZcOoGuxjILjIAxs3VFdDErzGEj4e%252F8GVcRWENZ1WGknhKYGaGepnx9KJPUadIpPbl2pYGyYjQy1XYDnG3gU%252FVA9DqoSfdp%252FTtT%252BlQ44sux2kuaU5KHZRhUiMQhxIdxjXXc%252BuUwvg%253D%253D%2522%252C%2520%2522version%2522%253A%25201%257D&openid.realm=https%3A%2F%2Fbuild.snapcraft.io
Content-Type: application/x-www-form-urlencoded
Content-Length: 2755
Cookie: _ga=GA1.2.1085461978.1517346120; _hp2_id.3194459691=%7B%22userId%22%3A%222956079548851845%22%2C%22pageviewId%22%3A%225221338519489150%22%2C%22sessionId%22%3A%225537546421872382%22%2C%22identity%22%3Anull%2C%22trackerVersion%22%3A%223.0%22%7D; sessionId=s%3ADjucRvCsIuTPihawscLRBk5xtSi2tik9.SIeTaFNwFmkrsufaHPBy1glGPhKQjSGRdvJSzKnLxhk
Connection: keep-alive
Upgrade-Insecure-Requests: 1

### Response

HTTP/1.1 302 Found
Date: Thu, 01 Feb 2018 01:24:48 GMT
Server: Apache/2.4.18 (Ubuntu)
X-VCS-Revision: 6901143c09760866d40005cdab56554cb9e912ad
X-DNS-Prefetch-Control: off
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Location: /login/failed
Vary: Accept
Content-Type: text/html; charset=utf-8
Content-Length: 70
set-cookie: sessionId=s%3ADjucRvCsIuTPihawscLRBk5xtSi2tik9.SIeTaFNwFmkrsufaHPBy1glGPhKQjSGRdvJSzKnLxhk; Path=/; Expires=Thu, 01 Feb 2018 03:24:48 GMT; HttpOnly; Secure
X-Request-Id: WnJsYH8AAQEAAE6ZGrgAAAA01
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive

### Request 2

GET /login/failed HTTP/1.1
Host: build.snapcraft.io
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://login.ubuntu.com/+openid?openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.sreg.required=nickname%2Cemail%2Cfullname&openid.ns.macaroon=http%3A%2F%2Fns.login.ubuntu.com%2F2016%2Fopenid-macaroon&openid.macaroon.caveat_id=%7B%22secret%22%3A%20%22J2Ou1uDwoB7yzgtl4vwYfMIBrFrQoHa7%2Bp2Jt15bV%2B%2BxdRdAm%2F6U%2FrvbNfVfyutc5Fz1vvie0K4BqrhqJpEx5Mm4cGwdtkslevGNg8nXvamDErgune85a3TCK1SiAfLagT9K4zDmEmr7rthzkMt0JUt6uX%2Fi%2F%2BkYXdMdvWU90ZjfpMPc0E3SPsWR7WfaxnpkWkMLMtAY0EYWSSZcOoGuxjILjIAxs3VFdDErzGEj4e%2F8GVcRWENZ1WGknhKYGaGepnx9KJPUadIpPbl2pYGyYjQy1XYDnG3gU%2FVA9DqoSfdp%2FTtT%2BlQ44sux2kuaU5KHZRhUiMQhxIdxjXXc%2BuUwvg%3D%3D%22%2C%20%22version%22%3A%201%7D&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=%7BHMAC-SHA256%7D%7B5a726c5e%7D%7B10vyyg%3D%3D%7D&openid.return_to=https%3A%2F%2Fbuild.snapcraft.io%2Flogin%2Fverify%3Fstarting_url%3Dhttps%253A%252F%252Fbuild.snapcraft.io%252Fuser%252Fdiddledan%26caveat_id%3D%257B%2522secret%2522%253A%2520%2522J2Ou1uDwoB7yzgtl4vwYfMIBrFrQoHa7%252Bp2Jt15bV%252B%252BxdRdAm%252F6U%252FrvbNfVfyutc5Fz1vvie0K4BqrhqJpEx5Mm4cGwdtkslevGNg8nXvamDErgune85a3TCK1SiAfLagT9K4zDmEmr7rthzkMt0JUt6uX%252Fi%252F%252BkYXdMdvWU90ZjfpMPc0E3SPsWR7WfaxnpkWkMLMtAY0EYWSSZcOoGuxjILjIAxs3VFdDErzGEj4e%252F8GVcRWENZ1WGknhKYGaGepnx9KJPUadIpPbl2pYGyYjQy1XYDnG3gU%252FVA9DqoSfdp%252FTtT%252BlQ44sux2kuaU5KHZRhUiMQhxIdxjXXc%252BuUwvg%253D%253D%2522%252C%2520%2522version%2522%253A%25201%257D&openid.realm=https%3A%2F%2Fbuild.snapcraft.io
Cookie: _ga=GA1.2.1085461978.1517346120; _hp2_id.3194459691=%7B%22userId%22%3A%222956079548851845%22%2C%22pageviewId%22%3A%225221338519489150%22%2C%22sessionId%22%3A%225537546421872382%22%2C%22identity%22%3Anull%2C%22trackerVersion%22%3A%223.0%22%7D; sessionId=s%3ADjucRvCsIuTPihawscLRBk5xtSi2tik9.SIeTaFNwFmkrsufaHPBy1glGPhKQjSGRdvJSzKnLxhk
Connection: keep-alive
Upgrade-Insecure-Requests: 1

### Response 2

HTTP/1.1 200 OK
Date: Thu, 01 Feb 2018 01:24:48 GMT
Server: Apache/2.4.18 (Ubuntu)
X-VCS-Revision: 6901143c09760866d40005cdab56554cb9e912ad
X-DNS-Prefetch-Control: off
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Type: text/html; charset=utf-8
ETag: W/"29fb-qzTwAsiZsFujtWDnEiQV+Q-gzip"
set-cookie: sessionId=s%3ADjucRvCsIuTPihawscLRBk5xtSi2tik9.SIeTaFNwFmkrsufaHPBy1glGPhKQjSGRdvJSzKnLxhk; Path=/; Expires=Thu, 01 Feb 2018 03:24:48 GMT; HttpOnly; Secure
Vary: Accept-Encoding
Content-Encoding: gzip
X-Request-Id: WnJsYH8AAQEAAE6ZGrkAAAA01
Content-Length: 3411
Keep-Alive: timeout=5, max=98
Connection: Keep-Alive

**Comment by bartaz** [comment]
Thanks for a detailed report.

I tried to reproduce it and it worked correctly for my own launchpad account - both when I was already logged in to it, and whey I was logging in from build snapcraft (for name registration).

Could you try again to check if it was a temporary issue or is it something different?

**Comment by diddledan** [comment]
I tried again this morning. It failed, so I opened the network pane of devtools to capture the full logs as I replicated it (this time with the "persist logs" option checked to retain logs of all the redirections), but the second attempt succeeded which made the network logs useless.

**Comment by bartaz** [comment]
Thanks for detailed report.

This issue seems to be appearing from time to time, and we still didn't manage to fully reproduce it and fix.

Closing this as it's a duplicate of a card we already have in backlog: #623
