### ISSUE TITLE
Queued builds are listed under "Previous builds"

### ISSUE THREAD

**Issue by diddledan** [canonical-websites/build.snapcraft.io#1056]
## Summary

When my first three builds, one for each architecture, failed I clicked the "build manually now" button and the new builds which are in the future as "building soon" are incorrectly categorised under the "previous builds" heading.

## Process

1. Get to a state where the previous three builds (one for each architecture) failed, and the "build manually now" button is activated. (it might be dependent upon the three failed builds being the very first three triggered after adding the repo.)
1. Click "build manually now" button
1. Observe that the newly queued builds are listed under "previous builds"

### Current
new pending builds are listed under "previous builds"

### Expected
pending builds either need to be listed separately or added to the "most recent build" section

## Screenshot

![image](https://user-images.githubusercontent.com/147548/35699677-9d5097c6-0745-11e8-9c6c-0bb8b68e0485.png)

**Comment by bartaz** [comment]
We updated the ordering of newly requested builds in #1052.

I cannot reproduce the issue currently, so hopefully the fix already in place is enough. If it happens again feel free to reopen or report it again.
