### ISSUE TITLE
Error:500 Server Error: Internal Server Error

### ISSUE THREAD

**Issue by kz6fittycent** [canonical-websites/build.snapcraft.io#1059]
## Summary

Receiving error: Error:500 Server Error: Internal Server Error
after successful build. 

## Process

Added new repo to build snap, snap successfully builds and fails to release.

## Current and expected result

Built a snap and wanted to publish it...it DID build but fails to release with error 500. 

## Screenshot

![screenshot from 2018-02-15 21-42-12](https://user-images.githubusercontent.com/14829816/36292684-2d8c46e2-1299-11e8-9e1c-9086aef2c91e.png)

**Comment by fefeh1** [comment]
I have the same error message.

![screenshot](https://user-images.githubusercontent.com/36348281/36292882-7ce1980e-129a-11e8-9437-cff496b8bfc0.jpg)

**Comment by cjwatson** [comment]
I haven't had time to investigate this (and am on leave today), but I think this is a store regression.  https://oops.canonical.com/oops/?oopsid=OOPS-5eac2e0127294ca19e822e73476cd435 is only accessible by Canonical staff but is I think representative.

**Comment by sparkiegeek** [comment]
As @cjwatson suspected, this is a regression in the store. I'm working to get the offending commit(s) reverted. Please bear with us

**Comment by sparkiegeek** [comment]
This should be fixed now, please re-open if you see it re-occur.

**Comment by cjwatson** [comment]
I've also just retried all the failed uploads from Launchpad.  (Apologies if that results in any slightly strange revision ordering in the store, but if so you should be able to sort it out with `snapcraft release` etc.)
