### ISSUE TITLE
504 Error when attempting to login to build.snapcraft.io

### ISSUE THREAD

**Issue by kz6fittycent** [canonical-websites/build.snapcraft.io#1065]
Receiving 504 error when attempting to login

See above, please. 

## Process

open https://build.snapcraft.io and attempt to login to add repo and start building new snap. But receive 504 error instead of successful login. 

## Current and expected result

See above

## Screenshot
![screenshot from 2018-02-27 23-39-12](https://user-images.githubusercontent.com/14829816/36771771-106271d0-1c18-11e8-99e1-ac22ec13e159.png)

**Comment by fefeh1** [comment]
I got the same error.

**Comment by bartaz** [comment]
Sorry for the issues.

There have been some sever restarts due to meltdown/spectre mitigations.
We redeployed build.snapcraft.io, so hopefully everything should be back to normal now.
