### ISSUE TITLE
build failing on download by ant build

### ISSUE THREAD

**Issue by bsutton** [canonical-websites/build.snapcraft.io#1067]
## Summary
I have a snap part which builds fine under lxd however it fails to build on the build servers.

[please describe the issue]
The error appears to indicate that it is unable to download a file which stops the build proceeding.
There appears to be an secondary error as there is an error regarding a python library however the snap in question doesn't use python for the build. The build uses ant.

## Process
Perform a manual build on the repo:
https://build.snapcraft.io/user/bsutton/tomcat-with-ssl-snap/158974

[list the steps to replicate the issue]
Attempt to build this project on the build server.
https://build.snapcraft.io/user/bsutton/tomcat-with-ssl-snap/158974

## Current and expected result
snap should build successfully.

[describe what happened and what you expected]
Error logs can be seen here:
https://build.snapcraft.io/user/bsutton/tomcat-with-ssl-snap/158974

Primary error:
```
estexist:
     [echo] Testing  for /root/tomcat-build-libs/commons-daemon-1.1.0/commons-daemon-1.1.0.jar
downloadgz-2:
    [mkdir] Created dir: /root/tomcat-build-libs
setproxy:
trydownload.check:
trydownload:
setproxy:
trydownload.check:
trydownload:
BUILD FAILED
/build/e4039a0b32e4bca67d290294684c86d6-xenial/parts/tomcat-with-ssl/build/build.xml:2623: The following error occurred while executing this line:
/build/e4039a0b32e4bca67d290294684c86d6-xenial/parts/tomcat-with-ssl/build/build.xml:2773: the archive download-604074008.tar.gz doesn't exist
```

Secondary error:
```
Total time: 0 seconds
ant
/usr/lib/python3/dist-packages/ndg/httpsclient/subj_alt_name.py:22: UserWarning: Error importing pyasn1, subjectAltName check for SSL peer verification will be disabled.  Import error is: No module named 'pyasn1'
  warnings.warn(import_error_msg)
/usr/lib/python3/dist-packages/ndg/httpsclient/ssl_peer_verification.py:25: UserWarning: SubjectAltName support is disabled - check pyasn1 package installation to enable
  warnings.warn(SUBJ_ALT_NAME_SUPPORT_MSG)
/usr/lib/python3/dist-packages/ndg/httpsclient/subj_alt_name.py:22: UserWarning: Error importing pyasn1, subjectAltName check for SSL peer verification will be disabled.  Import error is: No module named 'pyasn1'
```

## Screenshot

[if relevant, include a screenshot]

**Comment by bartaz** [comment]
As this project is only a front-end for builds that are running in Launchpad could you raise it there: https://bugs.launchpad.net/launchpad-buildd

Or ask on snapcraft forum (https://forum.snapcraft.io/c/snapcraft) where someone should be able to give more detailed help.

Thanks.

**Comment by bsutton** [comment]
Ok will do.

**Comment by bsutton** [comment]
I've moved this to launchpad so will now close this issue.

For reference:
https://bugs.launchpad.net/launchpad-buildd/+bug/1753340

**Comment by bsutton** [comment]
For the record this problem has now been fixed. The build servers now support a transparent proxy.
