### ISSUE TITLE
Internal Server Error on build

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#1069]
## Summary

I just visited build then clicked 'Sign in' and got "Internal Server Error ". I hit this a few times, just now. 

## Process

Visit build.snapcraft.io
Click sign in

## Current and expected result

Expect to get github sign in page

Got "Internal Server Error "

## Screenshot

![screenshot_20180305_135141](https://user-images.githubusercontent.com/1841272/36976139-d87bb09c-207c-11e8-8df6-bfdb6d747db6.png)

**Comment by bartaz** [comment]
There were some memcached errors at that time. Memcached services were restarted.

**Comment by evandandrea** [comment]
If we can’t talk to memcached or are getting invalid responses from it, can we show a page that says the service is experiencing problems?

**Comment by nottrobin** [comment]
@evandandrea I've tracked that request in https://github.com/canonical-websites/build.snapcraft.io/issues/1095 - closing this now.
