### ISSUE TITLE
build.snapcraft.io dashboard not updating

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#1070]
## Summary

Visiting https://build.snapcraft.io/user/popey I want to see when a thing last built, but the page seems to be dynamically refreshing and never stabilizing.

## Process

Visit https://build.snapcraft.io/user/popey while logged into site via my personal github account
Wait for statuses to update

## Current and expected result

Expect the statuses to update

Actually some do, then they revert back to 'Never built', whereas other stay as 'Never built'.

## Screenshot

![screenshot_20180305_140547](https://user-images.githubusercontent.com/1841272/36976628-8b471af8-207e-11e8-88fb-6d878e6b9fe9.png)

**Comment by bartaz** [comment]
This may be related to #1069 - looking at the logs it seems there are some issues with memcached.

**Comment by bartaz** [comment]
There were some memcached errors at that time. Memcached services were restarted.
