### ISSUE TITLE
Redirect 'My snaps' to snapcraft.io/account/snaps

### ISSUE THREAD

**Issue by Lukewh** [canonical-websites/build.snapcraft.io#1073]

**Comment by Lukewh** [comment]
Depends on https://github.com/canonical-websites/snapcraft.io/issues/393

**Comment by matthewpaulthomas** [comment]
As I explained in in [snappy-docs#376](https://github.com/canonical-docs/snappy-docs/issues/376), I think this is blocked by much more than just [snapcraft.io#393](https://github.com/canonical-websites/snapcraft.io/issues/393): it’s blocked on making the new pages more useful, for more publishers, than the old ones. That’s a standard that could be met in many different ways, but realistically won’t be met in Iteration 26.

**Comment by matthewpaulthomas** [comment]
…It sure won’t be met in Iteration 27, either. Probably a few months from now.

**Comment by bartaz** [comment]
Closing this PR per @therealjuan https://github.com/canonical-websites/snapcraft.io/issues/595.
