### ISSUE TITLE
Table not aligned

### ISSUE THREAD

**Issue by sergiusens** [canonical-websites/build.snapcraft.io#1077]
## Summary

The build summary for a specific build is not aligned in the table displayed at the top.

## Process

Go to https://build.snapcraft.io/user/CanonicalLtd/multipass/173622
This is at least experienced when using the latest firefox
```
sergiusens@mirkwood:~$ snap info firefox|grep installed
installed:   59.0.1-1 (68) 193MB -
```

## Current and expected result

Aligned headers and columns of course ;-)

## Screenshot
<img width="925" alt="image" src="https://user-images.githubusercontent.com/1146853/37828198-0b4529e0-2e79-11e8-844b-ae9bd5530e56.png">

**Comment by bartaz** [comment]
Yes, thanks for the report.
We have it in our backlog already: #1066

**Comment by bartaz** [comment]
Closing as duplicate
