### ISSUE TITLE
Incorrect links to report issues for snapcraft and snapd

### ISSUE THREAD

**Issue by sergiusens** [canonical-websites/build.snapcraft.io#1078]
## Summary

The links are incorrect in the footer, the currently point to:
- https://github.com/snapcore/snapcraft/issues for snapcraft, but https://github.com/snapcore/snapcraft/issues/new mentions Please log issues on the project's [bug tracker](https://bugs.launchpad.net/snapcraft) in its template
- https://bugs.launchpad.net/snappy is an abandoned bug tracking bucket by the snapd team

## Process

Take a look at the links by hovering over them or opening them?

## Current and expected result

The snapcraft tracker should be https://bugs.launchpad.net/snapcraft while the snapd one should be https://bugs.launchpad.net/snapd

## Screenshot

[if relevant, include a screenshot]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/1146853/37828289-696b67b4-2e79-11e8-9eec-1cb5cebdf68b.png">

**Comment by shivjoshi1996** [comment]
Also relevant to snapcraft.io and docs.s.io
