### ISSUE TITLE
Unclear how to get from front page to repos when signed in

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/build.snapcraft.io#1083]
When you are signed in to build.snapcraft.io, there is a link from the front page to your repos:

![2018-04-26 front page signed in annotated](https://user-images.githubusercontent.com/19801137/39301419-e90861e2-4946-11e8-807e-684f5cbf78dd.png)

And on every other build.snapcraft.io page, except for the repos page itself, there is a link to the repos page:

![build snapcraft io-my-repos-link annotated](https://user-images.githubusercontent.com/19801137/39301430-f36d1150-4946-11e8-9fa2-90cfff8075bf.png)

This might have been enough while build.snapcraft.io was more-or-less a standalone site. But now that it is integrated with (most of) the rest of snapcraft.io, it has a “My snaps” link in the header. That “My snaps” link does not go to your list of repos, but to a page that shows nothing about auto-building at all.

In the long run, this will be fixed by integrating auto-building with the rest of the “My snaps” UI. But in the short run, this confusion is easily fixed.

One way to fix this would be to add a link to the “My repos” page somewhere at the right end of the build.snapcraft.io header.

[Noticed by @therealjuan in [snapcraft-design#410](https://github.com/CanonicalLtd/snapcraft-design/issues/410).]

**Comment by therealjuan** [comment]
This will be covered with [#640](https://github.com/CanonicalLtd/snap-squad/issues/640)
