### ISSUE TITLE
Error:Unauthorized

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#1084]
## Summary

Trying to trigger a build manually of a snap and I keep getting "Error: Unauthorized". I have tried signing out and back in, but it keeps happening. I need to trigger these builds because there are security incidents in some parts.

## Process

visit build, login, click on one of my snaps.

## Current and expected result

![image](https://user-images.githubusercontent.com/1841272/39367343-60e5a6b0-4a2e-11e8-9a73-a655bc3e2cc8.png)

**Comment by popey** [comment]
This could be because I am middle clicking on projects which opens in a new tab. If I left click, it works. This slows down my workflow as I can't open 5 projects and then burn through them.

**Comment by bartaz** [comment]
I am able to reproduce the 'Unauthorized' issue when opening any repo link from 'My snaps' in new tab. First guess that it may be an issue with loading builds page via react router (in same tab) vs by browser in new tab.

Scrolling issue quite possibly related to the fact that BSI is single page app that doesn't really load new page, just renders new view and keeps scroll in same place (which we should fix).

**Comment by bartaz** [comment]
<img width="1849" alt="screen shot 2018-05-11 at 12 03 36" src="https://user-images.githubusercontent.com/83575/39919295-6c67aa8e-5513-11e8-996a-4daf8cee4b0a.png">

Error seems to be related to CSRF token being invalid. So we should look around this area.

Couple thoughts:
- possibly it's not needed to verify CSRF token on GET requests, especially for data from public APIs (such as list of builds)
- as CSRF tokens are stored in session - we may need verify if there are any issues with session storage

**Comment by bartaz** [comment]
CSRF issues were (potentially) fixed in #1003, but still there are some related problems.

Tried to open multiple tabs and manually trigger the builds and I still get `401 Unauthorized` in some of them with `{code: "token-not-valid", message: "CSRF token not valid"}` error.

Need some more investigation...
