### ISSUE TITLE
Add repo spins forever

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#1087]
## Summary

I am adding a repo to build. It never finishes.

## Process

Use build then leave the browser for 30 mins.
Add another repo.
When you click add, the icon spins foreve

## Current and expected result

I expect to get either a success or some kind of error message. I do not expect to have to open a javascript developer console to look under the covers to find out what's broken. 

## Screenshot
![image](https://user-images.githubusercontent.com/1841272/39812746-c85d8712-5385-11e8-899e-f0310f73770d.png)

**Comment by popey** [comment]
While this video shows the "sign in" part of the process, not the "add repo" part, it's indicative of the process. https://www.youtube.com/watch?v=TScyRQegeaE

**Comment by bartaz** [comment]
Should be fixed (or at least improved by fixes to #1003 and #1006)
