### ISSUE TITLE
Site shows no repos for a *very* long time

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#1088]
## Summary

Visiting the site to manage my repos, the page doesn't ever load.

## Process

Visit build.snapcraft.io and login

## Current and expected result

"No repos" - this is a lie - I have lots :)

## Screenshot

![image](https://user-images.githubusercontent.com/1841272/39813333-ea9ac6a8-5387-11e8-8148-a030e24f842b.png)

just as I took this screenshot the page updated!

![image](https://user-images.githubusercontent.com/1841272/39813353-014f7e98-5388-11e8-9606-0f3464fed99a.png)

**Comment by bartaz** [comment]
@popey Just for the sake of a scale - how many repos do you have on the list? 10+, dozens, 100+, more? First loading this long list, then polling for build status for each of them separately is probably killing it...

**Comment by popey** [comment]
~70. Here's a video showing what it's like today. https://youtu.be/GgKoCyilxWI

**Comment by popey** [comment]
In a brand new browser (chromium) which I have setup in order to work around the various issues in the store. I have left it open while I work in another window. I come back to it and *cannot* get it to refresh my repos.

![image](https://user-images.githubusercontent.com/1841272/39868802-12388ad0-5453-11e8-9949-852b8e5373b8.png)

I have:-

* Refreshed 
* Gone back to the previous package clicked 'lets see your repositories'
* Waited
* Filed this comment while I wait.

It doesn't load.

**Comment by popey** [comment]
I think I see what's going on here.

![image](https://user-images.githubusercontent.com/1841272/39916414-4ada52c4-5502-11e8-8ba4-080f825ade8c.png)

Myself, @evandandrea and @flexiondotorg have a bit of a quirky setup. We sign into build using our individual github accounts. We each may have some repos in our personal accounts. We also have a snapcrafters github org which we're all using to store some common repos. 

We all also have our own Ubuntu SSO accounts. In addition we have a shared snapcrafters SSO account. In the above screenshot (in a clean browser) I am logged into build using my personal github account, and the store as the snapcrafters SSO account. 

It looks like after logging into build as me, it's iterating over all the repos I have access (my personal popey and snapcrafters ones) and is failing to get the status of my personal ones from launchpad because I am signed into SSO (thus launchpad) as snapcrafters, not me. Snapcrafters SSO has no access to my snaps in launchpad.

**Comment by Greggless** [comment]
Something the Visual Studio App Centre does nicely is use a 'loading state' so rather than showing 'No repos' we have an interstitial state whilst we fetch the data. This would help with people with a large amount of data to pull and/or a slow connection.

![image](https://user-images.githubusercontent.com/23459065/40535535-4d6edbfe-6001-11e8-8561-97fa1d59b13d.png)

**Comment by bartaz** [comment]
Should be improved by fixes to #1003 and #1006.

Still, if memcache is expired first loading of a very long list of repos will take some time, but it shouldn't get stuck on 'No repos' anymore, but rather show spinner when loading or error if something went wrong.

**Comment by bartaz** [comment]
Follow up issue created: #1110

**Comment by matthewpaulthomas** [comment]
@Greggless That’s a good example of a [skeleton screen](https://docs.google.com/document/d/1UP7pD-jtX_mIn7Mw3YBS2SbKgDcNnLoMlvnAhzArfko/edit#heading=h.kxtbrcdfvroz). ZenHub and YouTube also use them heavily.

I didn’t spec this table to use a skeleton, for a couple of reasons. First, your number of repos is quite likely to be zero or one, in which case it would be weird for the page to suddenly shorten when it finishes loading. But that’s much less of an issue now that we have a sticky footer; much less would jump upward. Second, if the skeleton was visible for more than a couple of seconds, I thought we’d need to replace or add to it with something more animated anyway. But it didn’t occur to me that we could … make the skeleton itself animate. Like Kayak does:

![skeleton-animated-1](https://user-images.githubusercontent.com/19801137/40655925-aabc73fc-633a-11e8-8185-a7ced6ee2199.gif)
