### ISSUE TITLE
build.snapcraft.io doesn't allow custom snapcraft.yaml location

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [canonical-websites/build.snapcraft.io#1094]
## Summary

It seems that build.snapcraft.io [only allows snapcraft.yaml at `/snap/snapcraft.yaml`, `snapcraft.yaml` or `.snapcraft.yaml`](https://github.com/canonical-websites/build.snapcraft.io/issues/297), which is not always expected by the user.

For example one may write the snapcraft.yaml file at /snappy/snap/snapcraft.yaml or /distribution/snappy/snap/snapcraft.yaml, and should also be used as well.

Also I'm curious about the case where a project has pre-existing `prime`, `stage` and `parts` directories in the source-tree.

**Comment by evandandrea** [comment]
Hi @Lin-Buo-Ren,

Thanks for filing this. Supporting arbitrary locations for the snapcraft.yaml would require that everyone would have to specify this location when configuring build.snapcraft.io. This would create a more cumbersome experience than what they have today.

If you cannot write your snapcraft.yaml as .snapcraft.yaml, snapcraft.yaml, or snap/snapcraft.yaml in your project directory, I would suggest creating a separate repo for it. You can then set the `source:` stanza to point at your project repo. build.snapcraft.io watches for changes to `source:` repos and will build your snap whenever this changes, at most once a day.

The same applies for the prime, stage, and parts directories. If you already have these in tree for other purposes, I'd again suggest creating a separate repo for your snapcraft.yaml.

Thanks!

**Comment by frederickjh** [comment]
I know this has been closed, but is this information about the accepted build.snapcraft.io locations of snapcraft.yaml in the documentation? I search but could not seem to find it. Searching online for this information I ended up here.

**Comment by matthewpaulthomas** [comment]
@frederickjh [The “Snapcraft overview”](https://docs.snapcraft.io/snapcraft-overview/8940) says “`snapcraft init` … creates a buildable snapcraft.yaml template within a snap sub-directory relative to your current filesystem location.” And most of [the quick start guides](https://docs.snapcraft.io/creating-a-snap/6799) say “Snaps are defined in a single YAML file placed in the root of your project.” Both of these are allowed locations. [I’ve just suggested](https://forum.snapcraft.io/t/snapcraft-overview/8940/5?u=mpt) that this be made more obvious.
