### ISSUE TITLE
Channel tickboxes missing

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#1121]
I have seen this a few times, and sometimes refreshing the page "fixes" it. I am on the dashboard and clicked the "release" link for gitter-desktop which takes me to https://dashboard.snapcraft.io/snaps/gitter-desktop/revisions/38/release/ which has no channel selections.

![image](https://user-images.githubusercontent.com/1841272/41251480-f9b397fc-6db1-11e8-885f-d67d3b586ab4.png)

**Comment by evandandrea** [comment]
This belongs on snapcraft.io, not build.snapcraft.io. Moved to https://github.com/canonical-websites/snapcraft.io/issues/725
