### ISSUE TITLE
snap error of misisng yaml file 

### ISSUE THREAD

**Issue by sign-out** [canonical-websites/build.snapcraft.io#1125]
## Summary
snap error of missing yaml file but the file exists so i don't know what the real error is.
I'm sorry i can not be more helpful in the error. i also included my sysinfo screen for more info 
one thing of note is on both of them there bin folder only contains the receptive .desktop files  i think it may be important

## Process
on my system all i did was install obs-studio and QOwnNotes both with the same result shown in the screen shots attached 

## Current and expected result
I expected to have obs-studio launch normally
## Screenshot
![screenshot_20180628_230851](https://user-images.githubusercontent.com/24881930/42076419-e6b0a070-7b29-11e8-9fb5-f4f92a60a635.png)
![screenshot_20180628_231048](https://user-images.githubusercontent.com/24881930/42076420-e6dde79c-7b29-11e8-90ec-706d5f0d9bd4.png)
![screenshot_20180628_231903](https://user-images.githubusercontent.com/24881930/42076422-e6f7f998-7b29-11e8-80b3-1e4a1a662e4e.png)

**Comment by bartaz** [comment]
Hi, you don't seem to be using build.snapcraft.io (on-line service for building snaps). As far as I understand you are having issues with installing snaps, so this question/issue is better suited for Snapcraft forum: https://forum.snapcraft.io/categories.

**Comment by sign-out** [comment]
i cant mark this as closed  here is a link to the issue on snapd's forms 
https://forum.snapcraft.io/t/snap-error-of-misisng-yaml-file/6192
