### ISSUE TITLE
build.snapcraft.io home page is duplicated by snapcraft.io/build

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/build.snapcraft.io#1135]
## Summary

We just introduced a new https://snapcraft.io/build page that was meant to replace home page of BSI, but https://build.snapcraft.io still exists and is accessible.

## Process

1. Go to https://build.snapcraft.io
2. Click on (highlighted) Build in main nav
3. You end up on https://snapcraft.io/build which is similar but bit different

## Current and expected result

There should be only one copy of this page. If snapcraft.io/build is a new URL https://build.snapcraft.io should either redirect there or redirect to 'My repos' (authenticated part of BSI).

**Comment by shivjoshi1996** [comment]
duplicate

**Comment by matthewpaulthomas** [comment]
Of the nine issues reported since June 1st, none mention this page. So I’m fairly sure this isn’t a duplicate.

**Comment by matthewpaulthomas** [comment]
Sorry, I did not see that issue because it is incorrectly filed on snap-squad rather than build.snapcraft.io.
