### ISSUE TITLE
nodejs snaps fail to build because registry.npmjs.org is 503 (even though it does not seem to be down elsewhere)

### ISSUE THREAD

**Issue by mkg20001** [canonical-websites/build.snapcraft.io#1142]
## Summary

nodejs snaps fail to build because registry.npmjs.org is 503 (even though it does not seem to be down elsewhere)

## Process

Build a nodejs snap that requires npm packages, ex: https://github.com/mkg20001/libp2p-nodetrust

## Current and expected result

The snap should build as expected (tested locally and it works), but fails to do so because npm is returning 503's (but this does not seem to happen locally)
Logs: https://launchpadlibrarian.net/385290025/buildlog_snap_ubuntu_xenial_amd64_c9abcdad5062bdbd8f152153381ea7a2-xenial_BUILDING.txt.gz

## Screenshot

[if relevant, include a screenshot]

**Comment by cjwatson** [comment]
This is https://bugs.launchpad.net/launchpad-buildd/+bug/1781970.  I'll close this issue since it doesn't require separate action in build.snapcraft.io itself - once it's fixed in launchpad-buildd then that will deal with the BSI case too.
