### ISSUE TITLE
Header doesn’t highlight what section you’re in

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/build.snapcraft.io#1145]
1\. Go to [build.snapcraft.io](https://build.snapcraft.io/).
2\. Choose “Set up in minutes”.

What happens:

1\. “Build” is highlighted.
![build snapcraft io-build-highlighted](https://user-images.githubusercontent.com/19801137/45021656-055e9600-b02a-11e8-900f-286c9579b8a6.png)

2\. “Build” is no longer highlighted.
![build snapcraft io-build-not-highlighted](https://user-images.githubusercontent.com/19801137/45021705-29ba7280-b02a-11e8-8c49-a26cc76ab60c.png)

What should happen:
2\. “Build” is still highlighted.

**Comment by therealjuan** [comment]
This is incorrect because it should highlight your account name as Build only should highlight the homepage whereas the build functionality lives underneath the account section.

**Comment by therealjuan** [comment]
You are not on the build section because you are visiting items from your account dropdown and "Build" is disappearing soon as it will live as just a panel on the homepage.
