### ISSUE TITLE
Your session has expired. Link refreshes to wrong place

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#1146]
## Summary

"Your session has expired. Reload the page and sign in again." has a link which, when clicked takes you to https://snapcraft.io/ when I never went there to start with, but started at https://build.snapcraft.io/. I shouldn't be taken to a different site when reloading

## Process

Go to build.snapcraft.io and sign in
Go and have coffee, play fuseball or chat with co-workers
Time passes
Touch the page again, get a dialog like this.

![image](https://user-images.githubusercontent.com/1841272/45294051-fa0bde80-b4f1-11e8-8d9b-821096592471.png)

Click the link. 

## Current and expected result

Current: End up on snapcraft.io
Expected: End up on build.snapcraft.io

**Comment by bartaz** [comment]
As part of recent changes https://build.snapcraft.io home page is now redirecting to https://snapcraft.io/build which I guess is main reason of the confusing behaviour of the reload link.

**Comment by popey** [comment]
I didn't end up at https://snapcraft.io/build though. I ended up at https://snapcraft.io

**Comment by popey** [comment]
Is there any chance this (seemingly papercut) can be fixed? It's still throwing me off every time my session expires. Here's a gif showing what happens. The link says "build.snapcraft.io" but it doesn't go there. All I did was hit refresh in the browser, get the error banner, click the link and get sent to the wrong place.

![peek 2018-11-29 14-58](https://user-images.githubusercontent.com/1841272/49230432-8fc75380-f3e7-11e8-9e8c-03ca5cb2596c.gif)

**Comment by bartaz** [comment]
OK. I see what happens there. A crazy chain of redirects/sign-outs.

Behind the scenes the 'Reload this page' link signs out of build.snapcraft (to make sure session is properly cleared both client side and server side), but build.snapcraft sign out now also redirects to snapcraft.io sign out. So you are actually logged out both from build and snapcraft.io making to land on snapcraft.io home page.

Obviously, you just want your build session refreshed.
So, not completely trivial, but will try to fix that.

**Comment by OddBloke** [comment]
Has this fix been deployed yet? I hit this on Thursday.

**Comment by bartaz** [comment]
Yes, it was not deployed yet. Should be live now, sorry for the delay.

**Comment by OddBloke** [comment]
No worries, just checking that it hadn't regressed or anything. Thanks for the fix!
