### ISSUE TITLE
/user/repo pages no longer public

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#1164]
I couldn't find a pre-existing bug for this, but apologies in advance if I was using the wrong search terms. build.snapcraft.io/user/repo now require you to be logged in. We had designed these pages to be publicly shareable, but I think this was accidentally changed during the reworking of snapcraft.io/build.

**Comment by cjwatson** [comment]
#1148 is related, though I'm not sure whether it's precisely identical.

**Comment by cjwatson** [comment]
Actually, I think it is.  I previously closed your very similar #1149 as a duplicate of it :-)

**Comment by evandandrea** [comment]
Ugh, sorry.
