### ISSUE TITLE
Snaps with "base: core18" are built in a xenial environment

### ISSUE THREAD

**Issue by jhenstridge** [canonical-websites/build.snapcraft.io#1185]
## Summary

I recently updated one of my snaps to use the `core18` base snap.  When build.snapcraft.io triggered a rebuild, it failed due to building in the wrong environment.

## Process

Register a Github repository containing a snapcraft project that references the `core18` base.  My snap was https://github.com/jhenstridge/portal-test-snap-pkg/

Trigger a build either manually or by pushing a commit.  Here is the Launchpad URL for one of my builds: https://launchpad.net/~build.snapcraft.io/+snap/0b98fdfa15531019f18b4dab4ed2bd2d-xenial/+build/403212

## Current and expected result

The build log shows that it is starting with a xenial chroot.  The expected behaviour is to use a bionic chroot.

**Comment by jhenstridge** [comment]
It would also be nice if selection of the build environment was done on a per-build basis rather than once when registering the package.  In my case I just merged a PR that added `base: core18` (among other things), and it would be nice if that was enough to trigger the change in the build environment.

**Comment by shivjoshi1996** [comment]
@cjwatson Could you confirm that you have started this work, or work related to this?

**Comment by cjwatson** [comment]
@shivjoshi1996 Yes, I started it a few days ago.  Tracking as https://bugs.launchpad.net/launchpad/+bug/1812985.  (We will indeed likely need a small tweak to BSI at the end of it, but not much.)
