### ISSUE TITLE
Auto promote Edge to Stable

### ISSUE THREAD

**Issue by JackDandy** [canonical-websites/build.snapcraft.io#1186]
## Summary

Every time pushed to GitHub, I have to wait before being able to promote a build to stable at SC site. 

## Process

Push to repo at GitHub that is set up to send a request on push to SnapCraft.

## Current and expected result

A build is triggered, succeeds but only updates the edge channel even though confinement is `strict`.

Expected: Some way of enabling auto promote to stable so that there is no need to hang around waiting for 30-60 mins (or hours even) in order to manually promote from edge to stable.

Note: is the purpose of `snapcraftctl set-grade "stable"` in `override-pull:` supposed to do what i am asking ? If yes, then this is failing.

```
    override-pull: |
      snapcraftctl pull

      [ -z $(grep -o 'xx:xx:xx' CHANGES.md) ] && grade=stable || grade=devel
      snapcraftctl set-grade "$grade"
```

**Comment by matthewpaulthomas** [comment]
Auto-promoting would be one way to solve this problem. Another way would be a setting for which level auto-builds should be released to. For example, they might release to `stable` without using `edge` at all.

**Comment by therealjuan** [comment]
Thanks for raising this problem. Auto-promotion to stable channels is not something that we are considering in the upcoming roadmap as part of our design but we will work on improving the way builds and releases can work together on snapcraft.io.

**Comment by JackDandy** [comment]
Well it's a shame that this isn't regarded important enough because this is a real pain in the release flow when a build takes 4-6 hours due to all builders at launchpad being tied up and then we have to keep coming back to check "is it done yet?" in order to make your Snapcraft site current with a release - sigh!

**Comment by JackDandy** [comment]
If you or I trigger an auto image build on Docker, we don't need to be a nanny and go and check it has done what the automation was set up to do, that is, build an image. You email and let us know when to trigger a build due a security update requirement, which is great, but this requirement that forces us to go in and promote a Snapcraft build is simply bizarre. 

Six months have passed, and unfortunately, still no sign of improvement to this fundamental operational process, worse, I have the most strange related bug which I will report in another issue. 

I do hope someone will look at this one seriously though.
