### ISSUE TITLE
snap missing from list and cannot be added again

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#1198]
## Summary

Some of my snaps are missing from the big list in build.snapcraft.io. If I try and add them, I am unable to as it says they're already there.

## Process

1. Be me or snapcrafters - have a ton of repos
2. Note opentoonz is missing from the list
3. Try and add it to the list
4. failure.

Get a 400 error

```
{status: "error",…}
payload: {code: "lp-error", message: "There is already a snap package with the same name and owner."}
code: "lp-error"
message: "There is already a snap package with the same name and owner."
status: "error"
```

```
{"status":"error","payload":{"code":"lp-error","message":"There is already a snap package with the same name and owner."}}
```

**Comment by bartaz** [comment]
Looks like an issue we have reported for a while: #1181, so closing this one as a duplicate
