### ISSUE TITLE
Unable to pair with public organization repo

### ISSUE THREAD

**Issue by MarcoFalke** [canonical-websites/build.snapcraft.io#1200]
I can not pair an organization repository, even though the account I am using has the required rights. Moreover, the repository is public and it is not possible to just specify an URL to the public repo and trigger builds manually. See also https://github.com/canonical-websites/build.snapcraft.io/issues/1191#issuecomment-418279854 which questions why those permissions are needed in the first place.

I suspect that for some reason, the build site blindly requires an admin account to pair the repository, even though a non-admin user account can have all necessary permissions. This is confusing, especially given that no permission would be required at all and (similar to other build services) a simple URL to the public repo could be used to fetch the yaml on manual or scheduled builds.

**Comment by bartaz** [comment]
We require admin permission to be able to set up webhook to build on commit.
While in theory it's not necessary with daily or manual builds to have a webhook, we currently don't have any UI for setting webhooks later if user wants to add repo without them first.

As this seems like a very similar issue to #1191 I'll close this one to keep the discussion in one place.

**Comment by MarcoFalke** [comment]
An alternative is to use the lauchpad backend to build:

*    Log into https://launchpad.net with your Snap Store credentials, the ones you want to publish the snap as
*    Create a new Launchpad project, e.g. your-app-snap
*    Create a code import of the branch that has your snap yaml
 -      Select the project you just created
        Name it
        Use https://github.com/bla/bla for the URL
        Target version control system is Git
*    Once your code imports are in place, go to the page for the project you created and click on the Code link
*    Click on the URL for the imported branch, then "Create snap package"
*    Set up this automatic snap build

-       Name it your-app-snap-branch00
        Leave owner and series as-is
        Select all the architectures you wish to build for
        I'd suggest ticking the build source tarball option
        Tick automatically build when branch changes
        Tick automatically upload to store
        Put the registered snap name in the registered store package name field
        Tick the edge box
        Click create snap package
