### ISSUE TITLE
Rust builds have been broken for over two months now

### ISSUE THREAD

**Issue by kornelski** [canonical-websites/build.snapcraft.io#1203]
## Summary

Rustup has suddenly [changed its interface](https://github.com/rust-lang/rustup.rs/issues/945), and broke compatibility with snapcraft Rust plugin that used `--prefix` feature.

There exists a fix for it now, but it hasn't made its way to build.snapcraft.io yet.

## Process

Try building any Rust project, e.g. https://build.snapcraft.io/user/kornelski/gifski

## Current and expected result

> Failed to run '/build/gifski/parts/gifski/rust/rustup.sh --prefix=/build/gifski/parts/gifski/rust --disable-sudo --save'

## The fix

https://bugs.launchpad.net/snapcraft/+bug/1809259
https://github.com/snapcore/snapcraft/pull/2431

Could you apply the fix to the snapcraft version used on build.snapcraft.io?

**Comment by Lin-Buo-Ren** [comment]
As the fix is implemented since Snapcraft 3.1 and build.snapcraft.io is already shipping Snapcraft 3.2 this should no longer happen (unless you're still using the legacy snapcraft syntax, which requires backporting the fix to the legacy Snapcraft).

**Comment by Lin-Buo-Ren** [comment]
Yep, [it appears that you're using the legacy snapcraft recipe syntax](https://github.com/ImageOptim/gifski/blob/master/snapcraft.yaml), migrating to the new one that uses the `core18` base snap should solve this problem.

**Comment by Lin-Buo-Ren** [comment]
You might want to hold this off for a while as I (may) be making a patch for this one, it is very similar to the recent snap I'm working with and it seems to be interesting enough to invest my time in.

**Comment by kornelski** [comment]
Thank you for looking into this!
