### ISSUE TITLE
Duplicate builds are triggered when registering the snap to build.snapcraft.io

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [canonical-websites/build.snapcraft.io#1205]
## Summary
I just registered my snap to BSI and noticed this:

![screenshot](https://user-images.githubusercontent.com/13408130/54592362-29824180-4a67-11e9-8472-f80c188a005f.png)

2 identical builds is triggered simultaneously, wasting build farm resources.

## Process

1. Register a repo
1. Access the repo build page

## Current and expected result
Only one set of the build is triggered

**Comment by bartaz** [comment]
Thanks for the report. I tried it myself on a test repo and indeed there are duplicated builds (not all of them in my case):

<img width="835" alt="Screenshot 2019-03-19 at 10 06 10" src="https://user-images.githubusercontent.com/83575/54593392-bf4daa80-4a2e-11e9-8b4f-31238cef3528.png">
