### ISSUE TITLE
Invesigate solutions for dealing with container and presentational components

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#287]
As discussed in:
https://github.com/canonical-ols/build.snapcraft.io/pull/239#discussion_r103424695

---

Copied from Trello card: https://trello.com/c/Y32bOilM/324-invesigate-solutions-for-dealing-with-container-and-presentational-components
Labels:

**Comment by katiefenn** [comment]
K: 3
B: 4
R: 4
C: 4
