### ISSUE TITLE
Prepopulate registered snap name in template snapcraft.yaml [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#328]
1. Add a new repo that doesn’t have a snapcraft.yaml.
2. Register a snap name.
3. Choose “Not configured”.
4.Choose “Get started with a template”.

What happens: The GitHub editor shows text that (a) does not include your newly-registered snap name, and (b) suggests that you use “snapcraft register”.

What should happen: The GitHub editor shows text that (a) includes your newly-registered snap name and (b) does not suggest you need to register a(nother) name.

---

Copied from Trello card: https://trello.com/c/9NBxTYe2/224-prepopulate-registered-snap-name-in-template-snapcraft-yaml
Labels:

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.30j8f330tbd6): “If you have already registered a name for this snap, the template should use that name; otherwise, it should contain ‘`# name: Uncomment this after registering a name on build.snapcraft.io.`’.”

**Comment by evandandrea** [comment]
There was some confusion on this issue in the weekly prioritisation call. To clarify the current experience, you're presented with a template like this:
<img width="666" alt="screen shot 2017-03-15 at 13 49 59" src="https://cloud.githubusercontent.com/assets/1523179/23951581/5c1cfbb8-0986-11e7-8e79-25cbd6e6dbaa.png">

There are three problems:
1. The registered name, when one exists, is not populated into the yaml template (the original request in this issue).
1. When no name is registered (nothing forces you to do name registration first), the template will use "my-snap-name" which is already registered by someone else. You'll get an error to that effect in build.snapcraft.io.
1. In the case where no name is registered, `snapcraft register <name>` as presented in the template likely won't work. Chances are they haven't created an SSO user yet, which they would need to `snapcraft login` with before running `snapcraft register`.

Matthew's proposal goes some way to fixing this, thank you. I remain concerned that they won't know they need to update the snapcraft.yaml with the name they registered. I'd be happier with something like:
```
# Once you've registered a name on build.snapcraft.io, commit it as a new uncommented line:
# name: your-registered-name
```

**Comment by matthewpaulthomas** [comment]
Ok, [spec updated again](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.30j8f330tbd6).
