### ISSUE TITLE
[dashboard: add new repo]  Search through repos

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#330]
---

Copied from Trello card: https://trello.com/c/YEILhCOS/123-dashboard-add-new-repo-search-through-repos
Labels: 

---

[Design specification](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.dd21jq6zcpfz): “Whenever there are any usable repos, opposite ‘Choose repos to add’ should be a search field…”

**Comment by earnubs** [comment]
The large majority of users will likely have <1000 repos (?), so a single request could cover most users, this would mean the search could take place without a second or more fetch and be nice and responsive for the user.

You can still page as we do now, but the search wouldn't have to be via fetch if `total_repos < REPO_PAGE_LIMIT`.

**Comment by bartaz** [comment]
@earnubs Not sure what you mean. Why would search be any different then using user repos API?
As far as I can see in the docs, search API has 100 per page limit as well (docs)[https://developer.github.com/v3/search/#search-repositories].

Also using user repos API probably gives us more control over what repos we get and thanks to OAuth we get all the repos we were granted access to - without searching for them by user/org name.
