### ISSUE TITLE
[Add repos dialog] When adding repos we're still using the Vanilla table.

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#349]
The table we use for the **Add repos** dialog view is the Vanilla table style. When we go to dashboard we use the Maas style. We should use Maas style for both to be consistent.

---

Copied from Trello card: https://trello.com/c/FicZKwCw/276-add-repos-dialog-when-adding-repos-we-re-still-using-the-vanilla-table
Labels: design

**Comment by matthewpaulthomas** [comment]
It may save time to fix #538 at the same time as this issue.
