### ISSUE TITLE
Production builds link back to themselves

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#350]
---

Copied from Trello card: https://trello.com/c/KVuIKtSn/287-production-builds-link-back-to-themselves
Labels: Bug

**Comment by matthewpaulthomas** [comment]
This would be fixed by implementing the designed hierarchy navigation (#310).

**Comment by evandandrea** [comment]
Still happening:

<img width="375" alt="screen shot 2017-04-21 at 13 14 29" src="https://cloud.githubusercontent.com/assets/1523179/25276940/7c2d3f46-2694-11e7-86f9-cd1c6775de6d.png">

The "build number" and "result" fields should not be links.

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.lxvgcss3u749): “The table should be identical to the headers and equivalent row on the repo page, except that the build number should not link to the page you’re already on.”
