### ISSUE TITLE
[dashboard] alphabetically sort repositories and not paginate (0.5d)

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#383]
Comments:

@magdalena_mir I believe so - I don't think we do any particular sorting, and things will go wrong if people have more than whatever the page size is of enabled repositories.  Not very urgent though.,@colinwatson4 is it still valid?,**Linked to** Dashboard: enabled repos view: https://projects.invisionapp.com/d/main#/console/10245106/218034262/preview

---
Creator: Robin Winslow
Assignees: Colin Watson
Copied from Trello card: https://trello.com/c/nXOUoeD6/114-dashboard-alphabetically-sort-repositories-and-not-paginate-0-5d
Labels: copy to github

**Comment by earnubs** [comment]
Changes in #541 make this a lot easier.

**Comment by earnubs** [comment]
Repositories are already sorted alphabetically as that is the order gh defaults to sending them in (on `full_name`)?

**Comment by earnubs** [comment]
See also #330

**Comment by bartaz** [comment]
@earnubs GH sorts repos alphaetically (by `full_name`), but that's only used on "Add repos" view (where we list user GH repos). On "My repos" we are listing user snaps from LP, and I'm not sure if that list is sorted.

Having quick look at [the code](https://github.com/canonical-ols/build.snapcraft.io/blob/master/src/server/handlers/launchpad.js#L413-L487) it seems that we are right now just getting user snaps and then appending any of their organization snaps to the list. There doesn't seem to be any alphabetical sorting at any point.

@cjwatson Do you know any more about it?

**Comment by evandandrea** [comment]
I tried to batch together the remaining issues with the add repos page (there's no search, you have to scroll down to see the add button, the table isn't styled like the rest, …). Looking further, I don't see this as important compared to the other issues. Moving it down.
