### ISSUE TITLE
GitHub name only picked up on sign in

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#402]
Comments:

Not sure if we can/should fix that.

We only request user details on sign in and store them in session. It would be quite wasteful to request GH user details frequently just in case they changed their name.,Not on the MWC critical path.

If you forget to set your name in GitHub and notice this on build.snapcraft.io, it will only pick up you adding your name after you log out and log back in.

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/vGNiKWqK/290-github-name-only-picked-up-on-sign-in
Labels: Bug,copy to github

**Comment by bartaz** [comment]
Not relevant anymore
