### ISSUE TITLE
Active repositories placeholder component (0.5d)

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#411]
Comments:

@katie_fenn is it still valid? If not please move to done

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/dl1o8XyF/80-active-repositories-placeholder-component-0-5d
Labels: Question,copy to github

**Comment by bartaz** [comment]
Not relevant anymore
