### ISSUE TITLE
/api/launchpad/snaps/list?owner=foo should include builds info

### ISSUE THREAD

**Issue by earnubs** [canonical-websites/build.snapcraft.io#560]
Currently the list endpoint doesn't give info on build status for a snap, so we need to poll endpoints per snap, but if some of these details could be included in list api we could reduce requests on this page.

**Comment by cjwatson** [comment]
Some of my recent work has been in the area of establishing webhook communication from Launchpad to BSI for each snap.  I think it'd make more sense to defer this until after that's done, as we may be able to avoid polling build statuses from Launchpad altogether, or at least significantly reduce its frequency to serve only as a backstop in case of missed webhooks.

**Comment by bartaz** [comment]
@cjwatson If I understand it correctly it means that LP will be able to send data (like build statuses) to BSI via new webhooks, so BSI doesn't need to poll launchpad for new data?

From client point of view browser will still need to poll BSI server to fetch this data. But maybe at this point we will be able to construct BSI APIs in a way so they don't need to fetch per snap.

**Comment by earnubs** [comment]
There's possibly a case for websockets between client and bsi.
