### ISSUE TITLE
'fetching' state ui indicator is very often outside the viewport

### ISSUE THREAD

**Issue by earnubs** [canonical-websites/build.snapcraft.io#564]
For example on a long list of repositories in /dashboard/select-repositories the 'spinner' is at the top of the page but the actions next/prev are at the bottom; this means that any indication of activity is hidden, as it is outside the common users viewport.

Consider a 'fixed' position activity indicator, perhaps fixed at the top of the viewport, for example http://ricostacruz.com/nprogress/

**Comment by matthewpaulthomas** [comment]
Jamie and I hadn’t mentioned this before, because we didn’t want to confuse it with other changes to the “Add repos” dialog, but … This is one of the reasons that the dialog should always have a height that is less than the viewport height. The title (and eventually search field) should be fixed at the top; the selection count, “Cancel”, and “Add” fixed at the bottom; and the repos themselves in a scrollable pane between. Just like the Open dialog in G Suite or any local app.

Other reasons for doing this include:
- ensuring that the search field (#330) is always visible, so you don’t forget that you’re doing a search;
- ensuring that the count of selected repos is always visible;
- being able to get to the “Add” button without double the scrolling after the batch size is doubled (#379);
- being able to get to the “Add” button without having to scroll through _the entire list_ once pagination is replaced by loading-on-demand (#383).

**Comment by earnubs** [comment]
@matthewpaulthomas aaah, this is great, I had seen that before in the spec but forgot about it when I added this bug report. One other button you might want (if it's not there already, the spec isn't open here) is "refresh", to update the list of repositories without the user having to reload the page (technically it would update the repositories and snaps, to ensure the enabled repos where correct).

**Comment by matthewpaulthomas** [comment]
To clarify, loading-on-demand does not mean an extra button — just loading the next batch when you scroll (near) to the bottom of the existing batch, like long Waffle columns do.

Keeping the “Add repos” list up-to-date should not involve an extra button either, in the same way that keeping the “My repos” list up-to-date does not involve an extra button. Both places should use webhooks (plus window.addEventListener('online',…), perhaps) to notify them of updates to the repos.

Neither seem relevant to _this_ issue, except that automatic updating might mean the the spinner appears unexpectedly while you’re trying to read or select from the list. If so, then maybe centered over the list pane is the wrong place for it; maybe it should be in a corner of the dialog instead (perhaps just left of the Cancel button).

**Comment by bartaz** [comment]
> Keeping the “Add repos” list up-to-date should not involve an extra button either, in the same way that keeping the “My repos” list up-to-date does not involve an extra button. Both places should use webhooks (plus window.addEventListener('online',…), perhaps) to notify them of updates to the repos.

We can't use webhooks to know if user added or removed a repository.
To keep "Add repos" up to date when user is on this page we would need to periodically request current list of repos through GH API. It means sending frequent and in most cases unnecessary requests from browser to BSI and between BSI and GitHub.
It will be probably quite uncommon for a user to add or remove a repo on GH while they are on 'Add repos' in BSI. I don't think it's good to punish performance of all users by introducing polling for updated repos list to cover such corner case.

**Comment by matthewpaulthomas** [comment]
Fair enough. For the same reason, it’s not good to introduce an extra button to cover such a corner case when there’s a workaround available. The workaround is the same as it always has been for “Open” file dialogs: cancel it then reopen it.

[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.fok9l32yjsvk): “If the list of repos has taken more than two seconds so far to load, a spinner should appear centered in the list pane.”

**Comment by earnubs** [comment]
FWIW update on scroll is less reliable, more complex and not as clearly defined a UI as a "show more" button. I would advise not to go with update on scroll. :)

**Comment by matthewpaulthomas** [comment]
(I mentioned the other issues only to help explain the choice of solution for this issue. Please discuss tractability/fixing of the other issues in their own reports.)

**Comment by bartaz** [comment]
Fixed in #840 as part of #715
