### ISSUE TITLE
Next steps: update your install instructions [1]

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#655]
In addition to guiding the developer to promote to a stable channel we should also suggest they add the something like the following to their install instructions:

```
Install snap_name in seconds on Linux (Ubuntu and others) with:
  sudo snap install snap_name

Don’t have snapd installed? [Install it now](https://snapcraft.io/docs/core/install).
```

We could also give buttons to post this message on Facebook, Twitter, and Google+.

(It'd be nice to give them options to submit to Reddit and Hacker News, but we'd need a URL for the story and I don't think the builds page is what we want to present end users.)

- [x] update text to match spec ( #730 )
- [x] update layout to match spec (2 columns of copy, one for testing, one for install)
- [x] add copy to clipboard icon and behaviour (#732)
- [x] add Twitter share button
- [ ] add share URL buttons (facebook, g+, etc)

**Comment by matthewpaulthomas** [comment]
The instructions for (reposting elsewhere for) end users to install the stable build are very similar to the instructions for testers to install the latest build. So I think I’ll put them alongside each other, to help visitors understand how+why they differ.

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.dwvfeg899834).

**Comment by bartaz** [comment]
@matthewpaulthomas @nottrobin 
Do we have social icons we want to use there (with hover states)? I see some on ubuntu.com footer, but not sure if there are the ones (in these sizes) we want to have here?

**Comment by bartaz** [comment]
@matthewpaulthomas @nottrobin 
Do we have social icons we want to use there (with hover states)? I see some on ubuntu.com footer, but not sure if there are the ones (in these sizes) we want to have here?

**Comment by evandandrea** [comment]
@bartaz I can't speak to sizes, but there's the svg in https://github.com/canonical-ols/build.snapcraft.io/issues/654#issuecomment-298949804

**Comment by matthewpaulthomas** [comment]
I think those same icons would work at the same sizes.

Feel free to split out “Copy to clipboard” to a separate issue report.

**Comment by bartaz** [comment]
@evandandrea @matthewpaulthomas 
There is still an issue that was mentioned by @earnubs  on stand-up that it seems FB and G+ don't allow sharing/posting from API without link to share. And main descriptions suggests we don't want to share repo builds page URL.

Unless not sharing repo builds page URL only applies to Reddit/HN, and we are fine posting it to Twitter/Fb/G+.

**Comment by earnubs** [comment]
Do we have an asset available for the copy to clipboard icon?

What should be the behaviour for hover and click actions on copy to clipboard? (Colour change, messaging, eg. Should there be any instructional text on hover, should there be instructional text on click?)

**Comment by evandandrea** [comment]
>There is still an issue that was mentioned by @earnubs on stand-up that it seems FB and G+ don't allow sharing/posting from API without link to share. And main descriptions suggests we don't want to share repo builds page URL.

I'm inclined to take back what I said and suggest we add Hacker News and Reddit. I think you are more likely to be speaking to a strictly developer audience in those cases and thus using the repo builds page URL would be okay. @matthewpaulthomas, what are your thoughts?

**Comment by magdalena-mirowicz** [comment]
@earnubs if any work started on it please pause it and pick a card from top of the next column. Thanks

**Comment by magdalena-mirowicz** [comment]
@earnubs again sorry for confusion, it's fine to pick up as next priority

**Comment by earnubs** [comment]
@kwm14 Hello! Do you know if icons exist as assets for the various share buttons in this issue? Can you link them here?

Can you also describe the behaviour of the copy-to-clipboard button on hover, click, etc. Should it come with any tooltip (browser default or custom) to tell the user what's happening?

Same question for the other buttons, thanks! :)

**Comment by kwm14** [comment]
@earnubs Hello, in regards to the various share icons do you need them as a sprite or individual?

## Copy to clipboard
- by default button is white
- on rollover button turns grey (#f7f7f7)
- existing Vanilla component - https://docs.vanillaframework.io/en/patterns/code-snippet
- copy icon - https://assets.ubuntu.com/v1/994e60f9-get-link-url_16.svg

## Visual reference used on Juju
![screen shot 2017-05-12 at 16 24 22](https://cloud.githubusercontent.com/assets/17748020/26004973/7edb8242-372f-11e7-889c-7273e8c1200e.png)

**Comment by earnubs** [comment]
This seems quite different from the intention in the spec?

**Comment by kwm14** [comment]
@earnubs apologies for sending through wrong asset.

Please find attached 'copy to clipboard' icon as a sprite so it includes hover state, taking styling influence from an already existing code-snippet component.

**copy-to-clipboard icon**
https://assets.ubuntu.com/v1/78552050-copy-clipboard.svg

**Comment by earnubs** [comment]
@kwm14 no worries, thanks!

**Comment by earnubs** [comment]
@kwm14 the background colour of the initial state is the same as the background of the context in which this icon appears, can you also confirm the size as 44px?

![image](https://cloud.githubusercontent.com/assets/167440/26056635/1a0ca198-396e-11e7-9bb6-3a287aaa09fa.png)

**Comment by kwm14** [comment]
@earnubs Ah I didn't realise it was sitting on grey I assumed it was white, but this is the first time I've seen this screen.

- I've updated the colours to sit on background
- icon size to be 26px

**Updated copy-to-clipboard icon**
https://assets.ubuntu.com/v1/7e398214-copy-clipboard.svg

**Visual reference**
![clipboard-visual](https://cloud.githubusercontent.com/assets/17748020/26059177/b2cfba82-3978-11e7-8abc-245fa4460cfd.png)

**Comment by matthewpaulthomas** [comment]
To clarify, when you hover over the button, the text “Copy to clipboard” should appear [in grey next to the button](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.dwvfeg899834).

**Comment by bartaz** [comment]
I think there are 2 things blocking progress on this issue now.

1) I don't think we currently have any way in BSI to know that snap was released to stable channel and that's required to show and share install instructions of stable snap. Maybe there is a store API that gives this information but we are not using it.

2) From the comment on a spec https://docs.google.com/a/canonical.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit?disco=AAAABKatpCM it seems that the design is maybe not finished (doesn't suggest updating install docs?)

And one more that could use some clarification:

3) For social share buttons - could we have exact text and/or link that we want to share on different social media. The example in the descriptions uses Markdown which is not something we can use when sharing on Twitter, Facebook, etc. Should we share the same text, with link to snapd docs?

@evandandrea @matthewpaulthomas Could you clarify?

**Comment by cjwatson** [comment]
We can find out point 1 by using the same APIs that `snap info` and such use.  I think it's this:

  http://search.apps.ubuntu.com/docs/#snap-specific-endpoints
  http://search.apps.ubuntu.com/docs/#details

(The search.apps.ubuntu.com implementation is being replaced, but the APIs used by `snapd` will be preserved, so this should be fine.)

**Comment by evandandrea** [comment]
Reopening this as "add Twitter share button" and "add share URL buttons (facebook, g+, etc)" need to be done.

We can share the link to the builds page on social media. I was hesitant at first, but I've come around to the idea in https://github.com/canonical-websites/build.snapcraft.io/issues/655#issuecomment-300130899 as developers are most likely speaking to their developer peers in these early days of working on snaps.
