### ISSUE TITLE
“Add repos”: Only show spinner after 2 seconds

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#661]
@matthewpaulthomas mentioned that showing the spinner too quickly can lead users to feel the experience is slower than it actually is.

**Comment by matthewpaulthomas** [comment]
[From the spec](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.fok9l32yjsvk): “If the list of repos has taken more than two seconds so far to load, a spinner should appear centered in the list pane.”

The same problem happens with the “Repos to build” table: the table headers do not appear immediately, but a spinner *does* appear immediately, making the page much jumpier than necessary. So I’ve just specced [the same for that table](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.5pmm5n1ik1zh).

**Comment by bartaz** [comment]
To limit the scope of this issue only to "Add repos" I created a separate issue to do this in "My repos" (as this is a different piece of code anyway): #846
