### ISSUE TITLE
"Add repos" list: Prevent "cancel" button from jumping arround

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#662]
After you click the "Add" button, a spinner appears within the button:

![add spinner](https://assets.ubuntu.com/v1/5ce22467-jump.png)

This causes the cancel button next to it to "jump" left. This should be solved somehow.

**Comment by matthewpaulthomas** [comment]
[From the spec](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.d194grnp1ium) (emphasis added): “When you choose “Add”, everything in the dialog should become disabled, and the text of the “Add” button should _change to_ a spinner.”
