### ISSUE TITLE
Builds page: Create "Latest builds" table

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#671]
Separate out the "Latest builds" (for all architectures of the most recent build) from the previous builds.

As per [the spec](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.i96r6cjhu8ob).

**Comment by Greggless** [comment]
**Referencing an issue this affects**

[Daily builds phase 2](https://github.com/CanonicalLtd/snappy-design-squad/issues/109)
[Daily builds phase 3](https://github.com/CanonicalLtd/snappy-design-squad/issues/107)
[Daily builds phase 4](https://github.com/CanonicalLtd/snappy-design-squad/issues/108)

**Comment by bartaz** [comment]
Already fixed
