### ISSUE TITLE
Update user profile to use grey background

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/build.snapcraft.io#687]
As per new visual style user profile on top of the pages should have grey background:

<img width="788" alt="screen shot 2017-04-25 at 13 29 54" src="https://cloud.githubusercontent.com/assets/83575/25383208/52503834-29bb-11e7-8faa-4594e3be74ec.png">

**Comment by magdalena-mirowicz** [comment]
@bartaz could you add estimate in brackets please? thanks

**Comment by matthewpaulthomas** [comment]
Duplicate of #352.
