### ISSUE TITLE
Mock GitHub service is incomplete

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-websites/build.snapcraft.io#688]
Using the mock services as directed by `README` leads to failures to login.

Specifically BSI tries to query the DB using a GitHub user id which is missing from the mock layer - leading to

> 2017-04-26 09:32:03.165Z INFO express-access "HTTP GET /auth/authenticate" statusCode=302, url=/auth/authenticate, host=localhost:8000, connection=keep-alive, upgrade-insecure-requests=1, user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36", accept=tex
t/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8, referer=http://localhost:8000/, accept-encoding="gzip, deflate, sdch, br", accept-language=en-GB,en-US;q=0.8,en;q=0.6, method=GET, httpVersion=1.1, originalUrl=/auth/authenticate, , responseTime=4
> 2017-04-26 09:32:07.974Z INFO login "User successfully authenticated"                                    
> 2017-04-26 09:32:07.978Z INFO login "User info successfully fetched"                                          
> Unhandled rejection Error: Undefined binding(s) detected when compiling SELECT query: select "github_user".* from "github_user" where "github_id" = ? limit

**Comment by bartaz** [comment]
Mocks are no longer used or documented officially, so closing this as it's not likely to get any work any time soon.
