### ISSUE TITLE
"Built, failed to publish" doesn't explain why

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#714]
<img width="961" alt="screen shot 2017-05-04 at 08 28 23" src="https://cloud.githubusercontent.com/assets/1523179/25703483/c731133c-30a3-11e7-97b8-0e338e6c14f7.png">

When a build fails to publish there is no further explanation, and nothing suggests how you can resolve this (wait?).

**Comment by evandandrea** [comment]
@cjwatson do we have a quick way of finding out how often builds are ending up in this state, so we can prioritise fixing it?

**Comment by matthewpaulthomas** [comment]
To start on the design for this, I would need to know the possible reasons for failing to release. And if any of them involve a variable amount of text (like a release … log?), how long that text usually is.

**Comment by cjwatson** [comment]
Here are a couple of examples from https://bugs.launchpad.net/snapstore/+bug/1706786:

  "Waiting for previous upload(s) to complete their review process. If you want to prioritize this last one, go to the other upload(s) page in https://dashboard.snapcraft.io/ and click on the 'Reject and remove from review queue' button."

  "(NEEDS REVIEW) confinement 'classic' not allowed. If your snap needs classic confinement to function, please make a request for this snap to use classic by creating a new topic in the forum using the 'store' category and detail the technical reasons why classic is required."

I'm going on vacation soon so you'll have to figure out the details without me, but all the necessary data should be available quite easily using the Launchpad API.  You'll want to start with `lp.snaps.findByURLPrefix(owner='/~build.snapcraft.io', url_prefix='https://github.com/')` to get all the snap objects managed by BSI, then iterate over builds for each one and look at `snap_build.store_upload_status` (and `snap_build.store_upload_error_message` if you want the error message as well).

**Comment by evandandrea** [comment]
Another example:
>Can not create a new snap for mc, the name is already taken and owned by someone else.

From:
https://build.snapcraft.io/user/minio/mc/68830

**Comment by evandandrea** [comment]
When a new build comes in after one that failed automated review:
>Store upload failed: Waiting for previous upload(s) to complete their review process. If you want to prioritize this last one, go to the other upload(s) page in https://dashboard.snapcraft.io/ and click on the 'Reject and remove from review queue' button.

**Comment by bartaz** [comment]
@carlaberkers @matthewpaulthomas 

As suggested by @cjwatson I used LP API to fetch BSI snaps and their build statuses.

Possible upload status values are (as described in API:)
```
Unscheduled
Pending
Failed to upload
Failed to release to channels
Uploaded
```

Most of the builds were either `Unscheduled` or `Uploaded`.
I think there were just two in `Failed to release to channels` (they both had very cryptic `u'discharge'` error message).

`Failed to upload` was also a common one, with a very wide scope of possible error messages:

```
('Connection aborted.', error(111, 'Connection refused'))

(NEEDS REVIEW) 'daemon' should not be used with 'browser-support'
(NEEDS REVIEW) confinement 'classic' not allowed
(NEEDS REVIEW) confinement 'classic' not allowed. If your snap needs classic confinement to function, please make a request for this snap to use classic by creating a new topic in the forum using the 'store' category and detail the technical reasons why classic is required.
(NEEDS REVIEW) type 'gadget' not allowed
(NEEDS REVIEW) type 'kernel' not allowed

404 Client Error: Not Found
500 Server Error: INTERNAL SERVER ERROR
502 Server Error: Proxy Error

Permission is required: package_upload

Snap not found for name=green-recorder series=16

Waiting for previous upload(s) to complete their review process. If you want to prioritize this last one, go to the other upload(s) page in https://dashboard.snapcraft.io/ and click on the 'Reject and remove from review queue' button.

You must register agent-r name for 16 before uploading, please register it and try again.

[Errno 12] Cannot allocate memory

__all__: Can not create a new snap for keystone, the name is already taken and owned by someone else.

__all__: The new version submitted for 'my-first-snap786' does not match the upload ('my-first-snap2').

__all__: You do not have access to modify this package.

architectures: Invalid architecture specified in the manifest: amd64 armhf.

binary_sha3_384: A file with this exact same content has already been uploaded

confinement 'classic' not allowed with plugs/slots

desktop interfaces (unity7) specified without a corresponding meta/gui/*.desktop file. If using snapcraft, please see https://snapcraft.io/docs/build-snaps/metadata#fixed-assets. Otherwise, please provide a desktop file in meta/gui/*.desktop (it should reference one of the 'apps' from your snapcraft/snap.yaml).

desktop interfaces (unity7) specified without meta/gui/*.desktop. Please provide a desktop file via setup/gui/*.desktop if using snapcraft or meta/gui/*.desktop otherwise. It should reference one of the 'apps' from your snapcraft/snap.yaml.

human review required due to 'allow-installation' constraint from base declaration
human review required due to 'deny-connection' constraint for 'slot-attributes' from base declaration
interface 'X11' not found in base declaration


invalid description entry (empty)
invalid environment value for 'C_FORCE_ROOT': 1
invalid plugs entry (empty)

package contains external symlinks: usr/lib/jvm/default-java/jre/lib/security/cacerts

unknown plugs interface name reference 'X11'

version: Ensure this value has at most 32 characters (it has 42).
```

These range from networking issues, snapcraft.yaml errors, need for review, etc.
These text error messages are not very well structured and they clearly come from different parts of the store, so I guess it may be hard to categorise them and treat in some custom way on BSI side.
Possibly the best we can do is display these messages to developer on build status page as at least they give some suggestions about what may be wrong.

**Comment by carlaberkers** [comment]
It looks like those messages could be cleaned up a little bit so that they are more consistent and easier to pass on to the end user. Am I right to assume that we can write new messages and then could ask the store team to update them? 

Would it be possible (in this iteration, with minimal design input) to add an error message to the build status page and say something like "this build returned the following error: "{error_message}""
@matthewpaulthomas @nottrobin @bartaz?

**Comment by bartaz** [comment]
@carlaberkers @matthewpaulthomas 

Yes, changing the messages would need to be done on store part.
Looking at how different in structure they are they may come from different parts of the store, so making them all consistent may be a bit of an issue.

But at this point we can show the message, as it is in the UI (build page).
I created an example branch with simply showing the error message:
https://github.com/canonical-websites/build.snapcraft.io/pull/930

<img width="1055" alt="screen shot 2017-08-21 at 11 29 14" src="https://user-images.githubusercontent.com/83575/29518236-d60a0fd2-8678-11e7-89c2-5dcbaf499eba.png">

Some comments on visual design and/or copy of this are welcome.

**Comment by carlaberkers** [comment]
Thanks @bartaz, I think this is a good quick fix that will likely solve @evandandrea 's immediate concerns.

It would be good to let @matthewpaulthomas review your solution as well.

**Comment by matthewpaulthomas** [comment]
@bartaz That screenshot looks fine to me, good job. (In future we might alter the border color etc.)
