### ISSUE TITLE
KPI for successful edge publication

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#723]
Adding to bsi_developer_uptake we should have a KPI for when a github account has had a successful publication to edge. So the full funnel would be:
1. Enabled repo
1. Registered name
1. Added snapcraft.yaml (#706)
1. Requested build
1. Successful build and publish

**Comment by cjwatson** [comment]
We have almost all of this as a result of #566, but it seems that I didn't finish hooking it up to `bsi_developer_uptake` for some reason.
