### ISSUE TITLE
Add email addresses to requested GitHub permissions

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#731]
We'd like to send out an email announcing organisations support (once landed) to all GitHub users who have ever logged in. Can you please generate a list of these addresses in a secure internal location?

If we haven't requested that permission from GitHub, can we please start?

**Comment by cjwatson** [comment]
Can I ask, what was the point of having a UI widget on the site asking people to sign up for mail notifications when we implement org support, if we're just going to email all users anyway?

**Comment by bartaz** [comment]
It will be hard to get emails of 'ever' logged in users, as we never requested user email permission and we don't store user emails.

The only source of user email right now is mailchimp form gathering users interested in org/private repos support - and that was the feature that was meant to fulfil the need expressed in this ticket.

To provide any other list of user emails we would need to first start asking for permission to get user email from GH and start storing emails of logged in users (in DB?). This would obviously work only for users who log in after this feature is released.

**Comment by evandandrea** [comment]
We can send the org support mail to only those who have requested it. I've changed this issue to ask that we start asking for email addresses in the permissions we request from GitHub. This will form the foundation for onboarding mails.

Lowering the priority accordingly.

**Comment by magdalena-mirowicz** [comment]
@matthewpaulthomas I think it needs small copy update, hence the label

**Comment by matthewpaulthomas** [comment]
Straw-man proposal: “We use your e-mail address so we can contact you if you get stuck setting up your snap.”

It’s a straw-man proposal because it highlights two problems:
- It seems a bit pessimistic that we’re getting you involved in helping us prepare for the possibility that you give up.
- What if you don’t ever want us to e-mail you? On this page, the only obvious way to opt out would be to abandon the app altogether.

**Comment by evandandrea** [comment]
How about:

"We use your e-mail address to tell you about new features, and so we can
contact you if you get stuck setting up your snap."

>

**Comment by matthewpaulthomas** [comment]
That would solve the first issue … but would make the second slightly worse. “E-mail me about new features” seems like something that should be a setting, rather than a one-time permission.

**Comment by evandandrea** [comment]
Entirely fair. I'm happy with your straw-man.

**Comment by matthewpaulthomas** [comment]
Sorry I wasn’t clear: I was illustrating problems that need fixing, rather than making a serious proposal. I’m all in favor of using someone’s GitHub address to e-mail them, rather than making them enter their address separately. But if we e-mail people — or even suggest that we will — without a way to opt out, we risk getting a reputation for spam. Reported #785 for e-mail settings.

**Comment by evandandrea** [comment]
This has come back up as we want to send a single email to the people who have logged into the site but gone no further. I think we can make turning this off a setting, but it should be in the GitHub permissions we request (on by default).

**Comment by evandandrea** [comment]
It was pointed out that the emails themselves will have an unsubscribe link (as provided by Marketo), so we do not need a UI for the MVP of this.

**Comment by matthewpaulthomas** [comment]
Oh, excellent. And since GitHub doesn’t actually show app description text on the auth page any more, there’s no text to fine-tune; this can just go ahead. (If in some future design we [explained permissions next to the button](https://docs.google.com/document/d/1bdZnkT7UjLp9r8q2xoujYRGR--cz_fCgbyDNQEWXXfw/edit#heading=h.7i006o4j4ww3), we’d have to revisit what the text should be.)

**Comment by carlaberkers** [comment]
@evandandrea few questions
1. Who pointed this out? 
2. What happens when a user clicks the unsubscribe button on the email we sent them? What is the flow? How is the email data stored?

**Comment by evandandrea** [comment]
Sure @carlaberkers. @jamiebennett pointed it out. The email data will be stored inside Marketo. When they click the unsubscribe button they'll be taken to a manage subscriptions page like this:

![screen shot 2017-12-15 at 13 26 45](https://user-images.githubusercontent.com/1523179/34044164-dc2ec546-e19b-11e7-815e-a9ec293b51a1.png)

@Lewciie can confirm.

**Comment by Lewciie** [comment]
Yeah, I confirm that's the case, they can unsubscribe from subscription centre. I can additionally change the text on the Snapcraft.io box if that's to your preferences. I added that when we sent first comms regarding snapcraft a while ago.

**Comment by carlaberkers** [comment]
Great - adding to the backlog. @bartaz can you estimate how long this work would take you and if it would be possible to complete this side of Christmas? If so, can you add it to the small tasks epic? Thanks!

**Comment by bartaz** [comment]
@carlaberkers Is it just about adding additional permission which will give us access to user email - not doing anything with this email yet?

Or is it requesting email and storing it in database for logged in users? This would require changes to database and makes it bigger and not sure if we will fit it, knowing I'm off midday tomorrow.

**Comment by evandandrea** [comment]
Storing the email in the database so we can, at a later date, feed it into Marketo.

**Comment by bartaz** [comment]
I did a quick investigation and there are 2 ways we can get user emails.

1. Accessing **public** user email from their profile

To access a public user email (as set on their GH profile) we **do not** need any additional permissions. We get access to user public email once they log in and we can store it in DB.
I suggest this as a first implementation that I should be able to finish this iteration.

2. Accessing **private** user email

If user has set their email as private on GH we may still access it, but for that we need to ask for additional permissions when authorizing BSI (`user:email` access scope).
This will allow us to use email API to get access to all user email addresses (that they added to their GH profile). But this requires additional work to make a call to this API and store the response.
Also, some users (especially those who set their email to private on GH) may not want us to access it and therefore will not use BSI.

So, as much as it is possible I'd suggest not doing it, at least for some time. Let's start with accessing public email only and see if we are satisfied with how many users we can reach.

**Comment by bartaz** [comment]
As suggested above "phase 1" (accessing public user email) is implemented in PR #1037.

**Comment by carlaberkers** [comment]
Good call @bartaz, thank you!

**Comment by nottrobin** [comment]
> This has come back up as we want to send a single email to the people who have logged into the site but gone no further.

Can I just confirm - does this mean that everyone who authenticates with GitHub may get a one-time email from us asking if they need help, even though they have actively been told that would happen?

I just wanted to check - is that definitely compatible with the incoming GDPR? Since we're committed as a company to being proactive about compliance. I tried to do [a little light research](https://dma.org.uk/article/gdpr-consent-or-legitimate-interest-email-marketers-need-both) myself, but it seems both what counts as "consent" and "email marketing" are pretty nuanced.

**Comment by evandandrea** [comment]
>Does this mean that people who authenticate with GitHub may get a one-time email from us asking if they need help, even though they haven't actively been told that would happen?

The specs for the emails are [here](https://docs.google.com/document/d/1rWWBHupqu41yNyCTuO7vbTmGMFhbiATbcV3oP3RkB1E/edit#heading=h.2xb5nhocyadf) and [here](https://docs.google.com/document/d/1K-S-fTwETYwkgSZiLpXf0ZHucwpY76ZIfNpYD6fgKDU/edit#) (feedback welcome). We're covered by the privacy policy once they've created an Ubuntu SSO account. We should review with legal what wording should appear in the GitHub authentication box or following it to cover the steps prior to SSO account creation.

**Comment by carlaberkers** [comment]
@nottrobin My understanding is that is is more for tracking purposes and we don't send them emails until they have created an account. @evandandrea sent out a one time email to a selection of users but he was going to run that past Katherine in legal before sending it.

**Comment by evandandrea** [comment]
>@evandandrea sent out a one time email to a selection of users but he was going to run that past Katherine in legal before sending it.

Yup, Katherine approved the one-off emails.
