### ISSUE TITLE
"check out" colloquialism is particularly unfortunate in combination with "repos"

### ISSUE THREAD

**Issue by cjwatson** [canonical-websites/build.snapcraft.io#733]
If you're already signed in via GitHub but end up back on the landing page for whatever reason, then the site tells you "Hi $NAME, let's check out your repos", with a link to the "my repositories" page.  This is meant to be the colloquial use of "check out", as in "have a look at" ([Wiktionary sense 4](https://en.wiktionary.org/wiki/check_out)), but "check out a repository" is a thoroughly pervasive bit of technical jargon that means something entirely different, namely to get a local copy of the code in a repository ([Wiktionary sense 5](https://en.wiktionary.org/wiki/check_out)).

To avoid causing cognitive dissonance in those familiar with both senses or maybe even only the latter one, it would be good to find a different formulation for the landing page.

**Comment by matthewpaulthomas** [comment]
Good point, well spotted @cjwatson.

> Hi Bianca, let’s look at your repos.
> Hi Bianca, let’s take a look at your repos.
> Hi Bianca, let’s get caught up with your repos.
> Hi Bianca, let’s see what’s happening with your repos.

I like “let’s take a look at your repos”. [Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.o7vmcea3vzby).
