### ISSUE TITLE
Match snapcraft and the dashboard's use of publish and release

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#740]
It [was raised in the forum](https://forum.snapcraft.io/t/publish-or-release/518/11) that "publish" should be used when we speak about an ISV offering their applications and "release" for the action of making a version available (i.e. releasing into a channel).

If you disagree, by all means follow up on the forum thread. Otherwise, can we update the spec?

**Comment by niemeyer** [comment]
I'd be more clear: release is the action of making a version available _into a channel_.

**Comment by cjwatson** [comment]
The things we may need to change are:

 * Build statuses ("Built, publishing soon" etc.).  In this context, "publish" refers to all the stuff that happens in between the build finishing and the version being made available in a channel, i.e. both "push" and "release".  I don't think we should expose details such as "pushing soon", so this may need some creative rewording.
 * "Published to the snap store for testing" on the landing page.  Although this does require a push as well, perhaps we should be clearer, especially as the next bullet point is "When ready, promote to beta/candidate/stable" and yet we haven't mentioned "edge" so far.  Perhaps we should say something like "Released to edge on the snap store for testing"?
 * "Ready to publish to beta, candidate, or stable" and other similar messages on the build page.  Should definitely be "Ready to release".
 * "Published builds will remain published" when removing a repository.  I'm not sure about this, and it may need rewording.

Some ambiguous cases:

 * "Repos to build and publish" table.
 * "Registered for publishing" column in that table.
 * "Next, register a snap name for publishing" first-time text.
 * "To allow publishing, add that name to the snapcraft.yaml" if snapcraft.yaml doesn't contain a name.
 * "To publish to the snap store, this repo needs a registered name" and similar messages around name registration.

These should probably all be considered together, but I'm not sure what to do here.  "Registered for releasing" would definitely sound wrong.  They're mostly referring to how an ISV offers their applications, so maybe they can stay as-is?

On the other hand, these are probably fine:

 * "Auto-build and publish software for any Linux system or device", and other uses of "publish" on the landing page.

**Comment by niemeyer** [comment]
Yeah, per the thread in the forum, it's not wrong to say "publish a snap" in the sense that we have official terminology using "snap publishers". The cases we want to make sure are not mixed is when we're talking about the process of putting snaps into a channel. That's releasing. One curious side effect of these choices is that we can talk about releasing a snap again when it was already published (release into the stable channel), but it doesn't make so much sense to talk about publishing a snap that is already released. The snap was already published.. the question is just which channel we did release it into.

In that sense, that "Published builds will remain published" may even become "Released builds will remain published", which sounds nicer too as it gets rid of the repeated word.

**Comment by niemeyer** [comment]
The "publishing soon" does sound find to become "releasing soon" if that's what it's talking about.

**Comment by matthewpaulthomas** [comment]
Spec updated:
- “[Built, won’t be published](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.ii93oqyp8hl8)” > “Built, won’t be released” (“all the stuff that happens in between the build finishing and the version being made available in a channel” isn’t exposed anywhere else, so we don’t need to cover it here)
- “Built, publishing soon” > “Built, releasing soon”
- “Built, failed to publish” > “Built, failed to release”
- “Built and published” > “Built and released”
- “Auto-build and publish software for any Linux system or device” — unchanged
- “[Published for your users](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.o7vmcea3vzby)” > “Released for your users”
- “Publish your software for” — unchanged
- “Published to the snap store for testing” > “Released to the snap store for testing”
- “With Snapcraft, it’s easy to get your software published in the snap store” — unchanged
- “[Repos to build and publish](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.5c3e9xiupuq5)” > “Repos to build”
- “Registered for publishing” > “Registered for release”
- “[Published builds will remain published.](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.q8fitjuvz7vi)” > “Released builds will remain published.”
- “[Great! Next, register a snap name for publishing.](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.q0b3jpi4vtot)” > “Great! Next, register a snap name for releasing.”
- “To allow publishing, add that name to the snapcraft.yaml.” > “To allow releasing, add that name to the snapcraft.yaml.
- “[To publish to the snap store, this repo needs a registered name.](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.sf9bdlnfvbkg)” > “To release in the snap store, this repo needs a registered name.”
- “To publish to the snap store, you need an Ubuntu One account.” > “To release software in the snap store, you need an Ubuntu One account.”
- “[Ready to publish to beta, candidate, or stable?](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.lxvgcss3u749)” > “Ready to release to beta, candidate, or stable?”
- “Ready to publish to beta?” > “Ready to release to beta?”
- ‘(To publish to candidate or stable, you’ll need to stop using “confinement: devmode”.)’ > ‘(To release to candidate or stable, you’ll need to stop using “confinement: devmode”.)’
