### ISSUE TITLE
No explanation of why an organization repo is there

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/build.snapcraft.io#746]
If you sign in to BSI for the first time, but someone at one of your organizations has previously added a repo, it may not be obvious why it shows up in your list by default.

Perhaps there should be some sort of notification the first time you sign in, and/or a permanent explanation per-repo of how this repo ended up in your list.

**Comment by matthewpaulthomas** [comment]
Or maybe this could be a variation of the first-time flow. Instead of “Let’s get started! First, choose one or more GitHub repos for building”, it could say something like “Welcome! Colleagues have added {number} repo{s} already, but you can add more if you like.”

**Comment by evandandrea** [comment]
>“Welcome! Colleagues have added {number} repo{s} already, but you can add more if you like.”

I like that.

**Comment by matthewpaulthomas** [comment]
I’ve just had a go at this, but I can’t work out a clear definition for the condition. This text:
- should show up when you’ve just signed in for the first time, and have organization repos
- should still show up when you’ve signed in for the _second_ time, if you didn’t do anything the first time
- shouldn‘t show up any more if you’ve added any repos yourself
- shouldn’t show up after you’ve registered/changed/deregistered a name
- ideally shouldn’t show up any more after you’ve done anything with a snapcraft.yaml, but how could we tell if you did?
- _maybe_ shouldn’t show up any more after the first time you visit a build page, because then you might be a build engineer who is only on this site to monitor build failures
