### ISSUE TITLE
Incorrect style used on 'Cancel' button

### ISSUE THREAD

**Issue by kwm14** [canonical-websites/build.snapcraft.io#748]
Under 'Registered for publishing' dropdown we are using the wrong styling applied the 'Cancel' button. Currently we are using our link style rather than our button style.

### Current result
![screen shot 2017-05-11 at 12 32 47](https://cloud.githubusercontent.com/assets/17748020/25950341/8d0e0200-3652-11e7-9a52-2ec17b2433ab.png)

### Expected result
We should be using 'Base' button style as seen in Vanilla https://docs.vanillaframework.io/en/patterns/buttons
![screen shot 2017-05-11 at 14 05 12](https://cloud.githubusercontent.com/assets/17748020/25950443/edbbe45a-3652-11e7-9d6b-4fe12c79390f.png)

**Comment by bartaz** [comment]
Already fixed
