### ISSUE TITLE
It's not possible to retry a failed build

### ISSUE THREAD

**Issue by elopio** [canonical-websites/build.snapcraft.io#770]
I have a build that failed for the dillinger snap. It seems that a new release of the builders will fix my build, but I have no way to retrigger it.

Currently, I have to make an empty commit on the repo to get a new bulid. It would be a lot nicer to have a retry button next to failed builds. 

And in general, it would be nice to be able to make a build on demand, not just when things change in the repo. Sometimes, the remotes change but the repo stays the same, or things are fixed in one of the dependencies that don't require a snapcraft.yaml update.

**Comment by evandandrea** [comment]
@elopio @didrocks are there cases other than an external dependency referenced in the snapcraft.yaml changes that you would want to manually trigger a rebuild?

**Comment by didrocks** [comment]
We have the case I referenced in #901 when there aresome build failure due to the distribution itself or snapcraft not behaving correctly. For those, a way to retrigger a build without doing a dummy commit would be great to not pollute the git history on something unrelated.

**Comment by evandandrea** [comment]
Noted, thank you.

**Comment by bartaz** [comment]
It's possible to trigger built manually now, so this should help with that.
