### ISSUE TITLE
Confusing "copy" icon

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/build.snapcraft.io#779]
Our current "copy" icon does not look like a "copy" icon.

<img width="218" alt="screen shot 2017-05-17 at 08 57 00" src="https://cloud.githubusercontent.com/assets/83575/26141994/dd321cd6-3ade-11e7-857d-4fe4f9556cf8.png">

It's actually confusingly similar to icons used in text editors to insert a link. Below some examples from GitHub and TinyMCE:

<img width="789" alt="screen shot 2017-05-17 at 08 55 35" src="https://cloud.githubusercontent.com/assets/83575/26142011/f591745c-3ade-11e7-8757-aeea47bf10aa.png">
<img width="803" alt="screen shot 2017-05-17 at 08 55 58" src="https://cloud.githubusercontent.com/assets/83575/26142010/f58e25f4-3ade-11e7-8b50-b3bedd70cb67.png">

**Comment by matthewpaulthomas** [comment]
I reported [the same issue with Vanilla](https://github.com/vanilla-framework/vanilla-framework/issues/1073).

**Comment by matthewpaulthomas** [comment]
@spencerbygraves has now [produced a new icon](https://github.com/juju/juju-gui/issues/3000). I don’t know why it is in juju-gui rather than in Vanilla.

**Comment by matthewpaulthomas** [comment]
The icon has now been [fixed in Vanilla](https://github.com/vanilla-framework/vanilla-framework/pull/1119). Maybe adopting it could be an early step in the Vanilla transition, since it’s both a small change and a visible improvement.

**Comment by bartaz** [comment]
Already fixed.
