### ISSUE TITLE
Allow snapcraft.yaml to be in non-root repo dir

### ISSUE THREAD

**Issue by tvansteenburgh** [canonical-websites/build.snapcraft.io#784]
I have a repo with multiple snapcraft.yaml files in different dirs (see https://github.com/tvansteenburgh/etcd-snaps).  But it seems I can't choose one of these when I configure my repo on build.snapcraft.io - it expects the snapcraft.yaml to be in the root.

**Comment by bartaz** [comment]
build.snapcraft.io expects snapcraft.yaml to be in one of 3 standard locations:
'snap/snapcraft.yaml', 'snapcraft.yaml', '.snapcraft.yaml' (in this order).

Does that help?

**Comment by evandandrea** [comment]
We won't support looking beyond the places that @bartaz mentions. However, looking at how your repo is now laid out, you probably want branch support (#440).
