### ISSUE TITLE
No way to unsubscribe from e-mail

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/build.snapcraft.io#785]
For various reasons we might e-mail you:
- you got stuck setting up a repo
- a repo has entered an error state (e.g. someone corrupted the snapcraft.yaml)
- a build has failed

However, you should be able to use the site without us e-mailing you. If you cannot, you might start marking our messages as spam. (Which would become a problem for us, if enough of you use Gmail or other services that aggregate spam judgements across users.)

Therefore, there should be a setting for whether/when we e-mail you.

**Comment by therealjuan** [comment]
This is not happening anymore as we have moved to Marketo where every e-mail you receive includes an Unsubscribe link that takes you to the subscription center.
