### ISSUE TITLE
No clear brand name

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/build.snapcraft.io#790]
So far, we’ve been referring to build.snapcraft.io variously as “build.snapcraft.io” (as in the printed cards), “Build Snapcraft Eye Oh” (in conversation), “Build Snapcraft”, or sometimes “BSI”.

Most of these are inelegant for word-of-mouth marketing, and none of them would work well for the purpose of integrating the site with the rest of snapcraft.io. The name needs to:

- Be short enough that (when any “Snapcraft” is removed) it fits comfortably in a top-level navigation banner.
  [ Snapcraft • Learn • **???** • Publish • Forum • ꔮ biancapareira ▾ ]

- Be clear enough to convey, or at least suggest, the distinction between this site and the rest of the store admin, which I’m giving the working title “Publish” (uploading screenshots, setting prices, viewing installation stats, etc).

- Not imply that it’s the *only* way to build snaps.

Some possibilities to start off with:
- Snapcraft Auto-Build
- Snapcraft Repo Builder

**Comment by evandandrea** [comment]
I think "Build" is concise, accurate, and fitting to your top-level navigation. Doesn't the content within Learn already do enough to show that there's more than one way to build snaps?

**Comment by matthewpaulthomas** [comment]
I’m not assuming that people will go through the “Learn” section before navigating to the build.snapcraft.io section.

**Comment by evandandrea** [comment]
>So far, we’ve been referring to build.snapcraft.io variously as “build.snapcraft.io” (as in the printed cards), “Build Snapcraft Eye Oh” (in conversation), “Build Snapcraft”, or sometimes “BSI”.

To be clear, I don't think it warrants its own product name. "Snapcraft can automatically build and publish your application for the tens of millions of computers running Ubuntu, Debian, Fedora, OpenSuSE, Arch, Gentoo, Yocto and others."

>I’m not assuming that people will go through the “Learn” section before navigating to the build.snapcraft.io section.

So maybe it could be:
[ Snapcraft • Build • Publish • Docs • Forum • ꔮ biancapareira ▾ ]

I believe that GitHub forms the lion's share of our audience. It's 21 million developers and 59 million projects strong. My hope is that we can find a way of describing this part of Snapcraft which makes it the obvious default journey.

Along that path you're taught [how to write a snapcraft.yaml](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.30j8f330tbd6) ([if you even need to](https://github.com/electron-userland/electron-builder/wiki/Options#LinuxBuildOptions)), [iterating locally](https://snapcraft.io/docs/build-snaps/your-first-snap#run-snapcraft) as needed.
