### ISSUE TITLE
"Forbidden" error message without any explanation while registering a snap name

### ISSUE THREAD

**Issue by nataliabidart** [canonical-websites/build.snapcraft.io#792]
Hello,

While trying to QA a few things, I tried to setup a build for a repo I cloned, and after I logged in to Ubuntu One, and after choosing a snap name and clicking on "Register name" all I see is a "Forbidden" error that is very confusing, and there does not seem to be a way out.

See image:
![bsi-error-2](https://cloud.githubusercontent.com/assets/19535238/26218579/eba885ee-3be1-11e7-9d60-b8444a9a72ed.png)

(also note how my username, which is 39 chars long, clobbers the UI and make the name unreadable. This is now reported as #793.)

**Comment by bartaz** [comment]
It looks that we got `403 Forbidden` as a response from `/dev/api/register-name/`.

Which seems to mean there was something wrong with store sign in (macaroons)?
Still - it was not `401 Unauthorized`. And I'm not sure in what cases store API returns 403 error.

**Comment by bartaz** [comment]
@nataliabidart If you can reproduce this issue, could you look into browser dev tools and check error response from the store API?

It should contain more info about the error. Thanks!

**Comment by cjwatson** [comment]
403 is either "unsigned developer agreement" or "developer namespace not set".  I suspect the problem is simply that our code to automatically set the developer namespace where possible didn't work because https://code.launchpad.net/~nataliabidart/software-center-agent/namespace-as-long-as-username/+merge/324279 isn't on production yet.

**Comment by nataliabidart** [comment]
@bartaz: is quite likely that the 403 is caused by the reason mentioned by Colin, my bug report was mainly for showing a better user error and guide the developer on how to continue.

You can reproduce by creating an account in GH with an username of more than 30 chars (but before we roll out the sca code, which will not happen today cuz is Friday), and try to build any repo. The failure occurs at the registering name step.

Let me know if you need more info.

**Comment by gjsieben** [comment]
Same thing happens to me. Weird.

**Comment by bartaz** [comment]
@gjsieben Can you have a look at the browser console while trying to register the name and send us some details about any network response errors you see there?

There should be a call to register name API. If you could paste here a response body that could help identify the issue.

**Comment by the-mentor** [comment]
hi everyone,
i had the same issue.
I went to https://dashboard.snapcraft.io/dev/account/
and added a developer namespace to my acccount once i did that i logged out and back in to snapcraft.io and it fixed the issue.

**Comment by l-n-s** [comment]
Same happened with me. I needed to add developer namespace. "Forbidden" is not very clear error message for new users.

**Comment by l-n-s** [comment]
btw @bartaz, I've been looking at browser console. It returned 403 error and JSON in which it said something like "developer namespace is required" with that link https://dashboard.snapcraft.io/dev/account/. 

Now I've already created namespace, so I can't reproduce. Bug probably occurs when user creates fresh account on both login.ubuntu.com and build.snapcraft.io.

**Comment by jmewes** [comment]
I have the same problem on the attempt to try out Snappy.

![build_snapcraft_io_-_home](https://user-images.githubusercontent.com/5235584/31606073-6532401a-b268-11e7-95f3-a28fb6cfa7e1.png)

**Comment by jmewes** [comment]
As mentioned in the comment above, after clicking on https://dashboard.snapcraft.io/dev/account/ and then fill in the field for the developer namespace, the repo could be registered.
