### ISSUE TITLE
Workflow diagram is too big in Firefox

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/build.snapcraft.io#795]
Workflow diagram takes whole width of the landing page in Firefox, while it's scaled properly in Chrome.

Firefox:

<img width="582" alt="screen shot 2017-05-19 at 10 33 28" src="https://cloud.githubusercontent.com/assets/83575/26239770/a50b2842-3c7e-11e7-8090-92ca55ee7be1.png">

Chrome:

<img width="584" alt="screen shot 2017-05-19 at 10 34 14" src="https://cloud.githubusercontent.com/assets/83575/26239794/c2230b48-3c7e-11e7-93bc-a01d3d4a9237.png">

**Comment by matthewpaulthomas** [comment]
At any window width less than about 1030px, the diagram scrapes the edge of the window.
![build snapcraft io-796-workflow](https://cloud.githubusercontent.com/assets/19801137/26240070/a0da7ca2-3c77-11e7-8882-3a68d1687967.png)
