### ISSUE TITLE
[Gecko] Wordmark is 1px higher on build.snapcraft.io than snapcraft.io

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/build.snapcraft.io#800]
In Firefox:
1\. Go to [snapcraft.io](https://snapcraft.io/).
2\. Go to [build.snapcraft.io](https://build.snapcraft.io/).
3\. Look at the top left of the page while you switch between them.

What you see: The wordmark is 1 pixel higher on build.snapcraft.io than on snapcraft.io. This is because the header as a whole is 1px higher, and the logo is vertically centered in the header.

(The issue does not occur in Chrome, apparently because Blink allocates the extra 1px to something below the logo, while Gecko allocates it to something above the logo.)

What you should see: The wordmark is in exactly the same position.

**Comment by bartaz** [comment]
Issue seems to be visible in Firefox but not in Chrome.

Initially header styles from snapcraft.io were copied to BSI, but maybe something has changed in the meantime.

**Comment by matthewpaulthomas** [comment]
The height of the header is composed very differently in the two sites.

In snapcraft.io’s _header.scss, `.banner .logo {height: 48px;` is overridden by `.banner .logo {height: 48px;` (yes, exactly the same value) and then by `.banner .logo {height: 51px;`, resulting in a height of 51px.

In build.snapcraft.io, the logo image itself has `height="28"`, and then style.5eb7b1482e4b75767a13.css says `.header__logo___2dJVQ {`…`padding:11px 0}`, resulting in a height of 28px + 11px + 11px = 50px.

**Comment by matthewpaulthomas** [comment]
@kwm14 Peter said you’re the person to ask: Which site is correct? It’s possible that snapcraft.io is correct and build.snapcraft.io’s copy was inaccurate; that snapcraft.io’s header has recently changed deliberately; or that snapcraft.io’s header has recently changed accidentally.

**Comment by bartaz** [comment]
It may have happened that BSI header changed deliberately or accidentally somewhere on the way between prototype and current version.

I would suppose that snapcraft.io version is more up to date, so likely it's BSI that should be fixed to accommodate the style.

**Comment by kwm14** [comment]
@matthewpaulthomas Looking on https://docs.vanillaframework.io/en/patterns/navigation which is the latest version of Vanilla, the navigation height should be `48px`. So it suggests that snapcraft.io is using the correct version.

![screen shot 2017-05-23 at 09 34 49](https://cloud.githubusercontent.com/assets/17748020/26345637/6d19d67a-3f9b-11e7-90c6-720ab1d31786.png)

As @bartaz suggests maybe BSI header was accidentally changed between prototype and current version.
