### ISSUE TITLE
Add build.snapcraft.io to Works with GitHub

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#804]
GitHub launched [Works with GitHub](https://github.com/works-with) and [Marketplace](https://github.com/marketplace) at Satellite this week. We don't meet the criteria for Marketplace yet, but we should get ourselves listed on Works With:

https://github.com/works-with/new

**Comment by nottrobin** [comment]
I'm happy to do this. Do we need to discuss what exactly we're putting in the various fields?

Suggestion:

Name of your integration: "build.snapcraft.io"
App’s website URL: "https://build.snapcraft.io/"
Description: "Automatically build and publish snaps directly from your GitHub repositories"

Thoughts?

**Comment by evandandrea** [comment]
I think we should call the integration Snapcraft, not "build.snapcraft.io". The description should be "Auto-build and publish software for any Linux system or device".

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://goo.gl/soMSoC).

**Comment by evandandrea** [comment]
Submitted a listing under the production Snapcraft account.

**Comment by bartaz** [comment]
I guess it's done: https://github.com/works-with?utf8=%E2%9C%93&query=snapcraft
