### ISSUE TITLE
Fixup README and onboarding process

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#805]
Run through the process of getting the codebase running locally for the first time, ready for new starters on the project.

If it's not thoroughly documented in the README etc., then update the README accordingly.

**Comment by nottrobin** [comment]
#700 should also be fixed in the process of this.

**Comment by richmccartney** [comment]
@nottrobin when going through the README.md I didn't incur any blockers or issues. So no updates are needed on my side. In regards to #700 I would suspect that issue is redundant as I had no difficulties in setup of the server for BSI.

**Comment by nottrobin** [comment]
@richmccartney sounds good. I'm sure #700 et. al is out of date, so please go ahead and close this if you're happy with the onboarding experience.

**Comment by richmccartney** [comment]
Closed.
