### ISSUE TITLE
Update repository references to the new location

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#806]
This repository has moved from https://github.com/canonical-ols/build.snapcraft.io/ to https://github.com/canonical-websites/build.snapcraft.io/.

Although references to the old URL should continue to work as GitHub will setup redirects, we should nonetheless update any references to the new location. E.g.:

- [ ] "Report an issue" in the site footer
- [x] [ols-jenkaas](https://code.launchpad.net/~cjwatson/ols-jenkaas/move-bsi-repo/+merge/324608)
- [x] [wiki](https://wiki.canonical.com/ProductStrategyTeam/WebDevelopment/build.snapcraft.io)
- [x] launchpad git-to-git import
- [ ] references in the codebase

**Comment by cjwatson** [comment]
I did ols-jenkaas a while ago (r426).
