### ISSUE TITLE
Builder doesn't pull submodules

### ISSUE THREAD

**Issue by daker** [canonical-websites/build.snapcraft.io#813]
I do have a snap that needs to pull a submodule, but the builder only run ```git clone``` instead of ```git clone --recursive``` which makes the build fail.

**Comment by cjwatson** [comment]
Please could you re-file this against https://bugs.launchpad.net/launchpad-buildd and then close this issue?

**Comment by daker** [comment]
https://bugs.launchpad.net/launchpad-buildd/+bug/1694413
