### ISSUE TITLE
Support building more architectures

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#819]
Currently, build.snapcraft.io only builds 2 architectures by default. We should somehow provide the option to build more, or build more by default. This might be through adding this information so `snapcraft.yaml` or store it locally to build.snapcraft.io.

**Comment by bartaz** [comment]
Launchpad UI has an option to choose the architectures when requesting builds.
But these are limited to architectures (I guess these are `processors` in terms of Launchpad naming) selected when the snap was created in LP.

<img width="896" alt="screen shot 2017-05-31 at 11 20 50" src="https://cloud.githubusercontent.com/assets/83575/26625307/fe5950da-45f3-11e7-9b02-60f973ef92c6.png">

So one thing is to make possible to create snaps with different architectures then current 'amd64', 'armhf' (when new repo is added, and maybe changing it later if LP API allows that).

Second thing would be to allow choosing the architectures when requesting new builds - but currently we don't have any manual way to request builds (that was already reported in #770).

**Comment by cjwatson** [comment]
See also #556.

**Comment by evandandrea** [comment]
Snapcraft will grow the ability to specify what architecture the snap should be built on. We should honour this (after it lands), rather than have duplicative UI for it:
https://lists.ubuntu.com/archives/snappy-app-devel/2016-April/000654.html

**Comment by evandandrea** [comment]
We now build on armhf, arm64, amd64, and i386. https://bugs.launchpad.net/launchpad/+bug/1770400 will cover not building in architectures you do not want. I think we can close this.

**Comment by cjwatson** [comment]
And for the record, I expect that to also make it possible to build on architectures not currently covered.
