### ISSUE TITLE
Get listed on Marketplace

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#822]
Tasks:
- [ ] Reach 1,000 oauth users
- [ ] Offer a paid tier
- [ ] Confirm with Legal that we can accept the [general requirements](https://developer.github.com/apps/adding-integrations/listing-apps-on-github-marketplace/requirements-for-listing-an-app-on-github-marketplace/) terms of the [developer agreement](https://help.github.com/articles/github-marketplace-developer-agreement/)
- [ ] Draft copy for listing
- [ ] Submit listing

See also #804, which covers "Works with GitHub."

**Comment by bartaz** [comment]
Marking it as Blocked for now, as there is not much we can do until we get close to 1000 users.

**Comment by evandandrea** [comment]
We have well north of that, I believe. I think the real blocker is a paid tier.
