### ISSUE TITLE
snapcraft.yaml is not found if master is not default branch

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/build.snapcraft.io#824]
Found when debugging report #823

We currently only build `master` branch (even if GH default branch is set to something different), but we search for `snapcraft.yaml` using GH API that defaults to default branch.

So if there is `snapcraft.yaml` file in master branch but another branch is set as default on GH we will not find this `snapcraft.yaml`.

We should make sure we ask specifically for `snapcraft.yaml` from master branch.

For reference GH API docs: https://developer.github.com/v3/repos/contents/#parameters

**Comment by cjwatson** [comment]
I agree that this is a problem, but I don't agree with your proposed solution; we should just use the default branch properly.  That's #783, so TBH I think this is effectively a duplicate.

**Comment by bartaz** [comment]
Right, when #783 lands it would fix this issue (although it would require snapcraft.yaml to exist in default branch rather than master) and make proposed solution obsolete.
