### ISSUE TITLE
failed RUST build

### ISSUE THREAD

**Issue by General-Beck** [canonical-websites/build.snapcraft.io#833]
https://build.snapcraft.io/user/paritytech/parity

**Comment by elopio** [comment]
This is a problem in the source entry in the snapcraft.yaml. Nothing affecting build.snapcraft.io.

The fix is here: https://github.com/paritytech/parity/pull/5781

**Comment by cjwatson** [comment]
Thanks.  Closing this per @elopio's diagnosis.
