### ISSUE TITLE
Tear down (and setup) log lines distracting

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#834]
![img_8784](https://user-images.githubusercontent.com/1523179/26893638-c95125be-4bb3-11e7-9a73-b8454f172961.PNG)

We display a few lines of tear down (and setup) around the snapcraft run, but I can't think of a situation under which these would be useful to the developer debugging their failed build (but do correct me if you can think of one).

These can be a distraction from the actual source of the failure, which my brain assumes will be on the very bottom of the log.

**Comment by cjwatson** [comment]
Can you please refile this against launchpad-buildd?

I don't think we should delete that log information entirely (some of it is occasionally useful depending on how severely the build explodes), but we could definitely make it less noisy.  In particular, the response to snapcraft exiting non-zero could easily not be formatted as a traceback, which would make a big difference.

**Comment by evandandrea** [comment]
[Done](https://bugs.launchpad.net/launchpad-buildd/+bug/1696951)
