### ISSUE TITLE
htmldoc19: Built, failed to publish

### ISSUE THREAD

**Issue by michaelrsweet** [canonical-websites/build.snapcraft.io#837]
My HTMLDOC project is building but not publishing. There doesn't seem to be any way to diagnose the problem...

**Comment by michaelrsweet** [comment]
I figured out the cause, but the build.snapcraft.io dashboard should probably either provide a link to the dashboard.snapcraft.io page or the errors that caused the publishing to fail.

**Comment by Awk34** [comment]
what was your issue?

**Comment by michaelrsweet** [comment]
The plugs value in the yaml file was missing a comma. This didn't get validated until the publication step (running snapcraft on my development VM didn't report a problem) and then the error message wasn't very useful - should probably suggest removing white space and adding commas between values if a plug name contains a space...

**Comment by Awk34** [comment]
Hmm, I removed some commented lines in my yaml I had and it seems to publish now, thanks for pointing me towards yaml validation

**Comment by matthewpaulthomas** [comment]
Sorry for the confusion. There seem to have been three issues here:
- Running snapcraft locally did not report the problem — please [report that for snapcraft itself](https://bugs.launchpad.net/snapcraft), ideally attaching your snapcraft.yaml to the bug report.
- build.snapcraft.io did not validate the snapcraft.yaml before sending it for release — #668.
- At the release step, there was no explanation of why the release failed — #714.
