### ISSUE TITLE
Debugging suggestions don’t include “snap try”

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/build.snapcraft.io#841]
According to @popey in [snapcraft.io#334](https://github.com/canonical-websites/snapcraft.io/issues/334), there is something called “snap try” that is useful for debugging.

build.snapcraft.io should include this in [the debugging suggestions for a failed build](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.xd4fat9opl48).

**Comment by cjwatson** [comment]
`snap try` is useless if the build fails.  You won't have anything to try.

**Comment by matthewpaulthomas** [comment]
Thanks, I misunderstood what “broken snap” meant.
