### ISSUE TITLE
Debugging suggestions don’t include strace

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/build.snapcraft.io#842]
According to @popey in [snapcraft.io#335](https://github.com/canonical-websites/snapcraft.io/issues/335), “strace and other tools … can be used to debug a broken snap”.

build.snapcraft.io probably should include these in [the debugging suggestions for a failed build](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.xd4fat9opl48).

This should be fixed at the same time as #841.

**Comment by cjwatson** [comment]
I don't think I agree with this.  Certainly, `strace` is useful if you build a snap and find that the result doesn't work: for example it's likely to tell you which system calls are failing under confinement.  By contrast, my experience is that `strace` is only quite rarely useful for debugging build systems: yes, it's occasionally useful if one is truly desperate, but more often than not it just produces vast swathes of output that isn't very informative.

I don't think @popey's advice for debugging broken snaps transfers well to debugging broken build attempts.

**Comment by matthewpaulthomas** [comment]
Thanks, I misunderstood what “broken snap” meant.
