### ISSUE TITLE
“Anything missing?”/“Return to repos list” jumps to the top of the page

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/build.snapcraft.io#853]
1\. Choose “Add repos…”.
2\. Scroll away from the top of the page (for example, to see all of the dialog on a small screen).
3\. Choose “Anything missing?”.
4\. Scroll away from the top of the page.
5\. Choose “Return to repos list”.

What happens:
3\. The page scrolls to the top.
5\. The page scrolls to the top.

What should happen:
3\. The page stays at the same scroll position.
5\. The page stays at the same scroll position.

**Comment by richmccartney** [comment]
This should be resolved by #856 PR :)
