### ISSUE TITLE
valid snap/snapcraft.yaml shows as "Not configured"

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#875]
I've run the [snapcraft.yaml](https://raw.githubusercontent.com/snapcrafters/github-desktop/af0a9055935828a8f3c7ac0284e363e235d23d7c/snap/snapcraft.yaml) for github-desktop through several yaml validators and not one is showing an error. Despite this, it's showing as "Not configured":

<img width="1050" alt="screen shot 2017-07-06 at 14 12 10" src="https://user-images.githubusercontent.com/1523179/27912517-28d05304-6255-11e7-800d-8ec22dc6778a.png">

**Comment by bartaz** [comment]
Our yaml parser throws an error:

```
duplicated mapping key at line 43, column 128:
     ...  $SNAP/opt/GithubDesktop/desktop
                                         ^
```

It seems `command:` line is duplicated in lines 41 and 43: https://github.com/snapcrafters/github-desktop/blob/master/snap/snapcraft.yaml#L41-L43

**Comment by evandandrea** [comment]
Gah, sorry about that. I can't believe the 5 options I tried all missed that.
