### ISSUE TITLE
Empty state for repos search

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/build.snapcraft.io#878]
When user is searching through their repos and they enter search text that doesn't match any repos we currently show empty list.

<img width="943" alt="screen shot 2017-07-07 at 16 20 55" src="https://user-images.githubusercontent.com/83575/27961891-7de6f740-6330-11e7-9f02-b9ca7cf48753.png">

This is not very helpful.

We should show some empty state. Maybe just a helpful text explaining that given search didn't return any results.

**Comment by bartaz** [comment]
@carlaberkers @matthewpaulthomas 

When developing search for repos we found out we don't have a design for an empty state. If we can have something simple designed we should be able to implement it with rest of the feature during this iteration.

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.ny53egfvpu3e):
> The status text should also update live to show the number of results, for example:
> - 3 matches in 73 repos (Any missing?)
> - 2 selected, 3 matches in 73 repos (Any missing?)
> - No matches in 73 repos (Any missing?)
> - 2 selected, no matches in 73 repos (Any missing?)

**Comment by bartaz** [comment]
@matthewpaulthomas Should we show "matches" in status text at all if there is nothing in search input (therefore all repos are shown)? I would guess that no, because we don't 'match' anything if user doesn't search, so:

If search field is empty:
- 73 repos (Any missing?)
- 2 selected in 73 repos (Any missing?)

If search field contains some text and matches some repos:
- 73 matches in 73 repos (Any missing?) - if search matches all repos
- 3 matches in 73 repos (Any missing?)
- 1 match in 73 repos (Any missing?)
- 2 selected, 3 matches in 73 repos (Any missing?)

If search field contains some text but matches no repos:
- No matches in 73 repos (Any missing?)
- 2 selected, no matches in 73 repos (Any missing?)

**Comment by matthewpaulthomas** [comment]
@bartaz That’s all correct, yes. (All the non-search status text in the spec hasn’t changed.) Thanks for checking!
