### ISSUE TITLE
Unable to remove a repo to build 

### ISSUE THREAD

**Issue by daylightbrightledlight** [canonical-websites/build.snapcraft.io#884]
## Summary

On my build.snapcraft.io user page (after the second step: _Choose a repo_), I am unable to remove a repo to build. After pressing the Remove button, nothing happens and the repo still remains on the list.

## Process

1. Go to https://build.snapcraft.io/user/USERNAME (replace `USERNAME` with your username)
2. Press on the little trash can icon
3. When asked "_Are you sure you want to remove this repo from the list?_", press the red `Remove` button

## Current and expected result

Current: Repo is not removed from the list
Expected: Repo should be removed from the list

**Comment by evandandrea** [comment]
@daylightbrightledlight can you open the javascript console (More Tools -> Developer Tools in Chrome) and paste any error that appears when you click the trash icon? If you then go to the Network tab, you should see a red item in the list. Please click that and copy the text from the Response tab here.

**Comment by Lukewh** [comment]
This doesn't seem to be an issue for me. 

@daylightbrightledlight if you're still experiencing this issue, please do provide your browser console output if there are any errors.
