### ISSUE TITLE
Never built message

### ISSUE THREAD

**Issue by gocarlos** [canonical-websites/build.snapcraft.io#897]
## Summary

Message saying that the snap was never built. The snap is already installed and I get emails with the new built notifications. 

## Process

push new code to github repository, from where the snaps are built. 
## Current and expected result

It should show the progress or the building. 
## Screenshot

![selection_012](https://user-images.githubusercontent.com/1331762/28501597-7b3a800a-6fdf-11e7-8ef2-13f4c7fc22d8.png)

**Comment by bartaz** [comment]
Does this still happen?
I can't find the mentioned snap (or repo) anymore, so I will close this.

But if you still experience this issue feel free to reopen and comment. Thanks.
