### ISSUE TITLE
Big dropoff of users during GitHub auth

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/build.snapcraft.io#907]
Currently, when users click one of the buttons on the front page that send them to auth with GitHub, [66% of them don’t come back](https://docs.google.com/presentation/d/1uAvKABnNIehm3Et_ePa-V79UBjELB_PAAWft3bEjrLE/edit#slide=id.g24a0fe9e5d_0_23). This is a much greater dropoff than the other steps we measure.

Possible treatments:

- If people don’t have admin access to the repo they want to build, or if they don’t want to grant Snapcraft admin access, this could be fixed by switching to daily builds by default (#826).

- If people would be happy to grant Snapcraft admin access to one particular repo, but not to all their repos, this could be fixed by switching to GitHub Apps (#906).

- If people are put off by the auth page in general, implementing an interstitial page that explains the permissions could help ([snapcraft.io-static-pages#348](https://github.com/canonical-webteam/snapcraft.io-static-pages/issues/348)).

- Alternatively, we could explain the permissions in or near the buttons on the front page.

**Comment by matthewpaulthomas** [comment]
While GitHub auth is the biggest dropoff, the dropoff rates do seem to follow a fairly predictable curve: the further you get, the harder you stick. It might be that the first step will always be the flightiest, no matter what we do.

For daily builds by default to make a difference, people would need to be (a) seeing the “Admin access” line, (b) deducing that they won’t be able to add the repo they want, and (c) bailing at the auth page instead of continuing to explore. That might be happening … but I’m skeptical. And as I understand it, daily builds by default would have a big drawback: after you’d committed your snapcraft.yaml, there would be a much longer wait for your first build.

**Comment by cjwatson** [comment]
We'd still do an initial build once the repository is fully configured and so on.  That initial build isn't triggered by a webhook today, so there'd be no reason to stop doing it once we're using daily builds instead of webhooks by default.

**Comment by matthewpaulthomas** [comment]
Oh, maybe I’ve been misunderstanding it this whole time. So how do we detect when snapcraft.yaml has been added/fixed without using a webhook? And whatever that mechanism is, why don’t we use it instead of webhooks generally?

**Comment by cjwatson** [comment]
During the setup phase?  In the absence of a webhook, we'd have to poll, which is expensive.  Webhooks are better in all ways except for the admin access requirement.

**Comment by matthewpaulthomas** [comment]
(I still don’t understand that, but it’s more relevant to #826 so I’ve raised it there.)

**Comment by bartaz** [comment]
I think this is more or less covered by work on "Daily Builds" and related features.

**Comment by matthewpaulthomas** [comment]
@bartaz Do you have any numbers to support the idea that daily builds reduced the dropoff rate to an acceptable amount? As I explained above, it’s possible, but there are reasons to doubt it, and there are other things that might improve the rate.

**Comment by bartaz** [comment]
Maybe @evandandrea would be able to give us some current numbers on that.

Actually the only difference visible to users on point of GH auth is asking for webhook read/write instead of webhook admin (that was done a while ago).
"Daily builds" were introduced very recently, just announced in the forum and not yet re-enabled, so I wouldn't expect any change from that in numbers.
