### ISSUE TITLE
Find out how to implement linting of snapcraft.yaml

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#909]
Where does the responsibility lie for linting snapcraft.yaml? Can it be done with `snapcraft` on the command-line, or does it need a separate tool?

Ultimately it would be nice if this linting could be done store-side so that BSI is simply retrieving the results of the linting through an API. Is there any way to implement this so that we are preparing for that future?

@cjwatson thoughts?

**Comment by matthewpaulthomas** [comment]
As far as I know, it can’t be done using snapcraft on the command line: I reported that as [Launchpad bug 1666161](https://launchpad.net/bugs/1666161), “Can’t dry-run a build to check snapcraft.yaml”.

**Comment by nottrobin** [comment]
Bartek wrote this in an email:

> Next related issue to fix after merging this one would be:
> https://github.com/canonical-websites/build.snapcraft.io/issues/668
> 
> YAML parsing error is already exposed to client app, so it would be about formatting error message and showing it in the dropdown. I'm not sure, but it seems that design is not really finished for that.

So maybe all we need for #668 is YAML validation, which would be fairly simple.

**Comment by evandandrea** [comment]
I think that's reasonable, and a good first step. The reported cases of this have all been invalid yaml, not a missing part definition.

Step two would be to validate against [the schema](https://github.com/snapcore/snapcraft/blob/master/schema/snapcraft.yaml). Step three would hand off that responsibility to snapcraft, where it could run deeper sanity tests.

**Comment by nottrobin** [comment]
Thanks @evandandrea, logged these decisions on #668, closing this now.
