### ISSUE TITLE
Does not use the name= parameter on name registration

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#927]
When clicking the link to register ffmpeg, I'm taken to the following URL:
https://dashboard.snapcraft.io/dev/snaps/register-name/

This requires that I fill in the snap name again. Instead, let's use the `name=` field:
https://dashboard.snapcraft.io/dev/snaps/register-name/?name=ffmpeg

**Comment by bartaz** [comment]
This seems outdated
