### ISSUE TITLE
Some builds are never attempted.

### ISSUE THREAD

**Issue by ElecProg** [canonical-websites/build.snapcraft.io#929]
## Summary

Builds don't start if there has been a build with a bigger id, or

And aren't even added to the list if there is an earlier build (which did not start) for the same architecture.

## Process

Unfortunately I do not know why builds are skipped.

## Current and expected result

Current: some builds do not start and as a result some are not even listed.  
Expected: all build are tried.

**Comment by ElecProg** [comment]
Okay, I seem to have been a little too early to open a ticket as there has been a build since the start of this issue. Sorry about that... Just wondering how often are older builds checked?

**Comment by bartaz** [comment]
If there is a build for given architecture waiting to be build new builds for same architecture will not be triggered (which may seem like they are missing from the list).

On the times of higher load some builds may wait quite long time until attempted which may cause this issue be more visible.

Thanks for the report.
