### ISSUE TITLE
“No repos” shown: “Cannot read property 'text' of undefined”

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/build.snapcraft.io#936]
I have about four repos set up in BSI, but the “My repos” table just says “No repos”.

If I choose “Add repos…”, then re-select one of my already-chosen repos, and choose “Add”, the button spins indefinitely.

Every 20 seconds this appears in Firefox’s Developer Console:
`GET XHR https://build.snapcraft.io/api/launchpad/snaps/list [HTTP/1.1 500 Internal Server Error ___ms]`

The full text of the response is:
`{"status":"error","payload":{"code":"internal-error","message":"Cannot read property 'text' of undefined"}}`

The problem occurs only on build.snapcraft.io, not build.staging.snapcraft.io.

**Comment by cjwatson** [comment]
It looks like the memcached units were rebooted and BSI failed to reconnect properly.  I restarted the BSI app servers and they sorted themselves out from there (although you may have to reload the page since your CSRF token may be invalid).
