### ISSUE TITLE
"Forbidden" when trying to register a name

### ISSUE THREAD

**Issue by wupeka** [canonical-websites/build.snapcraft.io#945]
## Summary
When trying to register a name for repo I get 'Forbidden' (with no explanation)

## Process
Enter any name in the box and press 'Register name'

## Current and expected result
The name should be registered, instead I get 'Forbidden'.

**Comment by bartaz** [comment]
Hi, your problem looks quite similar to something already reported before: #792 

Is this a new account you created? Possibly your store account is not fully configured. Could you confirm that going to https://dashboard.snapcraft.io/dev/account/ and adding any required missing information there fixes the problem?

When you get this 'Forbidden' error in build.snapcraft.io - could you check the browser console network panel for any error API responses? There quite likely should be some 403 or similar error response with JSON data. If you could check that and tell us what specific error you get it can help us debug this issue.

Thanks!

**Comment by wupeka** [comment]
Yep, the problem was with missing 'Developer namespace' setting in the profile.
