### ISSUE TITLE
cannot sign in to store

### ISSUE THREAD

**Issue by mwhudson** [canonical-websites/build.snapcraft.io#951]
## Summary

I go through the flow for adding a repo, get to https://build.snapcraft.io/user/mwhudson and when registering for release to the store I click the "sign in..." button, the cursor changes to a 'no more clicking' symbol for a few seconds and then it all goes back to how it was before.

I am logged into the store already, and have 2fa set up. Doing it all in an incognito window worked fine.

**Comment by evandandrea** [comment]
Hi @mwhudson! Can you open the javascript console before clicking "Sign in…" and see if any pages return a none-OK response? Please paste their return data here.

**Comment by mwhudson** [comment]
Of course it's working now. I did look in the console before reporting this and didn't see anything very interesting.

**Comment by bartaz** [comment]
There were some problems signing in recently (like #952).
Hopefully they were temporary issues with network or cache.
