### ISSUE TITLE
 `Error:Invalid association handle` trying to get build service to recognise registered snap

### ISSUE THREAD

**Issue by Ads20000** [canonical-websites/build.snapcraft.io#952]
## Summary

I’ve registered my snap using snapcraft register gifcurry-ads20000 but the build service doesn’t recognize that I have that name registered (that’s the name in my snapcraft.yaml) and then errors out when I try to log in via SSO.

Also [reported on the forum](https://forum.snapcraft.io/t/error-invalid-association-handle-trying-to-get-build-service-to-recognise-registered-snap/2074).

## Process

This is the process I went through:

- Fork https://github.com/snapcrafters/fork-and-rename-me using GitHub's [Import repository](https://github.com/new/import) feature
- Edit the `snapcraft.yaml` to an actual one that the build service accepts
- Change the name of the repo to `appname`
- Put the `name` in the `snapcraft.yaml` as `appname-developername`
- In Terminal, use `snapcraft register appname-developername`

### Current

![screenshot from 2017-09-10 10-40-20](https://user-images.githubusercontent.com/3178485/30269769-fa5de376-96e1-11e7-9b0f-384ff3a27eaa.png)

I hit Sign In... and get taken to Ubuntu SSO. I log in there, then I get one of the following errors: 

![screenshot from 2017-09-10 10-40-31](https://user-images.githubusercontent.com/3178485/30269777-0766d99c-96e2-11e7-940f-abdf885b034e.png)
![screenshot from 2017-09-10 10-39-29](https://user-images.githubusercontent.com/3178485/30269776-0757e4e6-96e2-11e7-9920-7bcf70d887e5.png)

As you can see, my `git-iplayer` repo is registered as `git-iplayer-ads20000` and the build service has no problem with that (except the build doesn't work because of a bug I've failed to fix, ignore that).

And here's the proof [my `snapcraft.yaml` has the `gifcurry-ads20000` name](https://github.com/Ads20000/gifcurry/blob/master/snap/snapcraft.yaml).

### Expected

The build service should just see that I have the repository registered.

## Screenshot

See above

**Comment by bartaz** [comment]
Hi @Ads20000, thank you for detailed bug report.

"Invalid association handle" error usually shows up when there is some problem with user session.

Could you sign out both from build.snapcraft.io and Ubuntu SSO (by going to https://login.ubuntu.com/ and clicking Log out)?
Or try to sign in and register name in browser Incognito/Private mode (to make sure you are using clean session)?

Let us know if problem persists.

**Comment by Ads20000** [comment]
That worked, thank you, though I don't know how it got to that state in the first place.

**Comment by joedborg** [comment]
I believe this is a duplicate of https://github.com/canonical-websites/build.snapcraft.io/issues/952

**Comment by Ads20000** [comment]
I'm confused, #952 is a duplicate of #952?

**Comment by joedborg** [comment]
> I'm confused, #952 is a duplicate of #952?

Sorry, my bad, i've updated the comment

**Comment by Ads20000** [comment]
Yes this is indeed a duplicate of #623
