### ISSUE TITLE
Can't register snap name

### ISSUE THREAD

**Issue by shepting** [canonical-websites/build.snapcraft.io#956]
## Summary

When adding a new repository, you can't register a new name (regardless of what you choose to name it).

## Process

 1. Register a new repository
 2. Try to register a name
 3. See the error "Forbidden" regardless of the type of name you try to use

## Current and expected result

Expected that I could register a name.

## Screenshot

![screen shot 2017-09-15 at 1 01 00 pm](https://user-images.githubusercontent.com/48065/30479594-3bb84cd0-9a16-11e7-9d92-b7d69c663b89.png)

**Comment by bartaz** [comment]
Hi, your problem looks quite similar to something already reported before: #792

Is this a new account you created? Possibly your store account is not fully configured. Could you confirm that going to https://dashboard.snapcraft.io/dev/account/ and adding any required missing information there fixes the problem?

When you get this 'Forbidden' error in build.snapcraft.io - could you check the browser console network panel for any error API responses? There quite likely should be some 403 or similar error response with JSON data. If you could check that and tell us what specific error you get it can help us debug this issue.

Thanks!

**Comment by bartaz** [comment]
Fixed by #979
