### ISSUE TITLE
Error tryign to create a snap

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-websites/build.snapcraft.io#966]
## Summary

I get an endless spinning wheel when click the green button.
Error from the newtowkr tab:
{status: "error", payload: {code: "github-snapcraft-yaml-not-found",…}}
payload:
{code: "github-snapcraft-yaml-not-found",…}
code:
"github-snapcraft-yaml-not-found"
message:
"Cannot find snapcraft.yaml in this GitHub repository"
status:
"error"
## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by bartaz** [comment]
@lyubomir-popov Are you still experiencing this issue? Can you add any repo?

**Comment by lyubomir-popov** [comment]
no, just tried and it proceeds to the next step.
