### ISSUE TITLE
Link to /create leads to 404

### ISSUE THREAD

**Issue by sanjacloud** [canonical-websites/build.snapcraft.io#969]
fixable in `src/common/components/repository-row/dropdowns/unconfigured-dropdown.js` with 

`const INSTALL_IT_LINK = 'https://docs.snapcraft.io/build-snaps/';`

**Comment by bartaz** [comment]
Thanks, we are already fixing this in https://github.com/canonical-websites/snapcraft.io/pull/82, but it wouldn't hurt to point directly to correct resource from here as well.
