### ISSUE TITLE
empty repo gives wrong error message

### ISSUE THREAD

**Issue by spruceriver** [canonical-websites/build.snapcraft.io#972]
I tried using an empty repo and it said my snapcraft.yaml was invalid.

<img width="1063" alt="screen shot 2017-10-06 at 12 26 27 pm" src="https://user-images.githubusercontent.com/31933866/31288178-d55e0c5e-aa91-11e7-9988-e11659f6f259.png">

**Comment by bartaz** [comment]
Thanks for the report. We will look into this.

**Comment by matthewpaulthomas** [comment]
Design spec updated:
> If the repo does not contain a snapcraft.yaml file (including if the repo is empty, #972), the cell should read “Not configured”, and clicking it should expand the row to reveal a panel explaining snapcraft.yaml.

**Comment by bartaz** [comment]
Fixed by #973
