### ISSUE TITLE
"Sign Out" link shows text cursor, doesn't look clickable

### ISSUE THREAD

**Issue by thomir** [canonical-websites/build.snapcraft.io#975]
## Summary

When signed in to build.snapcraft.io, the "Sign out" button in the top right of the page shows a text cursor (i-beam), rather than the usual cursor for clickable links (hand cursor). It's still clickable, it just doesn't look like it is.

## Process

* Sign in to build.snapcraft.io.
* Hover mouse over "Sign Out" button

## Current and expected result

Expect to see the hand cursor. Actually see the I-beam cursor.

## Screenshot

Unable to take a screenshot, since the cursor is hidden when screenshots are taken.

**Comment by bartaz** [comment]
@thomir Good catch. Thanks.

I can confirm this happens (MacOS Chrome, Firefox).
