### ISSUE TITLE
Client-side error reporting

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#978]
Can we investigate options for client-side error reporting? The human approach is error-prone. We currently ask users to open the developer console, switch to the networking tab, refresh the page, find any red requests, and copy and paste them into a new GitHub issue.

**Comment by evandandrea** [comment]
@nottrobin

**Comment by bartaz** [comment]
We now have sentry set up on BSI, so any unhandled JS errors will be reported.
