### ISSUE TITLE
Until the log api for launchpad isn't there we should probably link it

### ISSUE THREAD

**Issue by 3v1n0** [canonical-websites/build.snapcraft.io#987]
## Summary

No progress information is given to users about the status of their builds

And this is known as per #295, but until that is fixed, it would be probably better to link each build "In progress..." label to the https://launchpad.net/~build.snapcraft.io/+snaps related page.

Logcat is still enough to give the user an idea.

**Comment by evandandrea** [comment]
Is the issue that you don't see a streaming log, that you have to wait until the build is done to see the log?

**Comment by 3v1n0** [comment]
Yeah... I mean, I know where to go to catch them, but other users could not, so pointing to the proper builder in launchpad could be a good way to fill this gap, in the mean time.

**Comment by bartaz** [comment]
Initially the point was not to expose the launchpad internals too much (meaning not linking directly to LP UI).

So the question is if we want and can handle it somehow without updating LP to serve incremental log over API.

**Comment by 3v1n0** [comment]
I see the point, however in the mean time this is the quickest fix I guess, while having incremental and live logs needs to be indeed the final goal.

**Comment by evandandrea** [comment]
As @bartaz says, the workflow for build.snapcraft.io purposefully does not link to pages on Launchpad. It's a quick fix, but it comes at the cost of losing developers in a completely foreign user experience.

We do eventually want log streaming, and that's captured in #295. Let's move over to that.
