### ISSUE TITLE
Build triggering broken on staging

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#988]
Adding a repo and registering the name fails to trigger a build on staging:

https://build.staging.snapcraft.io/api/launchpad/snaps/request-builds
```{"status":"error","payload":{"code":"internal-error","message":"select \"build_annotation\".* from \"build_annotation\" where \"build_id\" in ($1, $2, $3) - permission denied for relation build_annotation"}}```

**Comment by evandandrea** [comment]
@cprov 👋

**Comment by cjwatson** [comment]
Fixed now via `GRANT ALL PRIVILEGES ON TABLE build_annotation TO "snap_build";`.  (There's some obscure bug in our DB charm setup that means this has to be done by hand when creating new tables; fortunately that's rare.)
