### ISSUE TITLE
Builds Stuck

### ISSUE THREAD

**Issue by Justinzobel** [canonical-websites/build.snapcraft.io#994]
## Summary

Builds stuck on page. Builds 100832-4 are set as "Building Soon" but aren't progressing.

## Process

Initiate a build by changing a package.yml or initial upload

## Current and expected result

Currently "Building Soon", I would expect after an hour or so the build would have processed

**Comment by bartaz** [comment]
@Justinzobel We've been having some issues with builders and there is long queue of builds scheduled.

It may take couple of more hours for the queue to clean up and service should be back to normal. Sorry for the issues.

**Comment by Justinzobel** [comment]
Wouldn't hurt to re-allocate some of the idle builders for other architectures to the arm64 / i386 queue :)

**Comment by cjwatson** [comment]
Heh.  Unfortunately we had a pile of security builds, the opening of the auto-sync from Debian for bionic, and one of our x86 cloud regions down for redeployment all at once; any one of those would have caused a bit of a backlog, but all three at the same time is certainly not ideal.

Anyway, I'm going to close this, as it isn't a code issue with build.snapcraft.io and there's nothing much we can do about it at the moment that we aren't already doing.

**Comment by cjwatson** [comment]
... but I've bumped your builds up the queue and they're building now.
